### ISSUE TITLE
The UTC time represented when the offset is applied must be between year 0 and 10,000.

### ISSUE THREAD

**Issue by mregni** [mregni/EmbyStat#1022]
```
2019-12-12 09:01:21.4455 [ERROR] MEDIASYNC-JOB	Can't seem to process show Brooklyn Nine-Nine, check the logs for more details! 
2019-12-12 09:01:21.4455 [ERROR] System.ArgumentOutOfRangeException: The UTC time represented when the offset is applied must be between year 0 and 10,000.
Parameter name: offset
   at System.DateTimeOffset.ValidateDate(DateTime dateTime, TimeSpan offset)
   at System.DateTimeOffset..ctor(DateTime dateTime)
   at System.DateTimeOffset.op_Implicit(DateTime dateTime)
   at EmbyStat.Common.Converters.ShowConverter.ConvertToEpisode(VirtualEpisode episode, Show show, Season season) in C:\Users\mikha\Documents\EmbyStat\EmbyStat.Common\Converters\ShowConverter.cs:line 163
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProgressMissingEpisodesAsync(Show show) in C:\Users\mikha\Documents\EmbyStat\EmbyStat.Jobs\Jobs\Sync\MediaSyncJob.cs:line 355
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.GetMissingEpisodesFromTvdbAsync(Show show) in C:\Users\mikha\Documents\EmbyStat\EmbyStat.Jobs\Jobs\Sync\MediaSyncJob.cs:line 306 System.ArgumentOutOfRangeException: The UTC time represented when the offset is applied must be between year 0 and 10,000.
Parameter name: offset
   at System.DateTimeOffset.ValidateDate(DateTime dateTime, TimeSpan offset)
   at System.DateTimeOffset..ctor(DateTime dateTime)
   at System.DateTimeOffset.op_Implicit(DateTime dateTime)
   at EmbyStat.Common.Converters.ShowConverter.ConvertToEpisode(VirtualEpisode episode, Show show, Season season) in C:\Users\mikha\Documents\EmbyStat\EmbyStat.Common\Converters\ShowConverter.cs:line 163
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProgressMissingEpisodesAsync(Show show) in C:\Users\mikha\Documents\EmbyStat\EmbyStat.Jobs\Jobs\Sync\MediaSyncJob.cs:line 355
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.GetMissingEpisodesFromTvdbAsync(Show show) in C:\Users\mikha\Documents\EmbyStat\EmbyStat.Jobs\Jobs\Sync\MediaSyncJob.cs:line 306
```

**Comment by mregni** [comment]
This issue should be fixed in the beta.15 release
