### ISSUE TITLE
Null ref exception in TVDB client

### ISSUE THREAD

**Issue by mregni** [mregni/EmbyStat#1029]
Running the sync takes a VERY LONG time and all shows return the same null ref exception.

```
9-12-13 14:38:40.1826 [INFO] MEDIASYNC-JOB	Lets start processing show 
2019-12-13 14:38:40.1826 [INFO] MEDIASYNC-JOB	Logging in on the Tvdb API. 
2019-12-13 14:38:40.1826 [INFO] THETVDB-CLIENT	Logging in on theTVDB API with key: XXXXXXXXXXXXXX
2019-12-13 14:38:40.7966 [INFO] MEDIASYNC-JOB	Found 169 show for Hentai library 
2019-12-13 14:38:41.2000 [INFO] THETVDB-CLIENT	Call to THETVDB: https://api.thetvdb.com/series//episodes?page=1 
2019-12-13 14:38:41.3277 [ERROR] MEDIASYNC-JOB	Can't seem to process show Ai no Katachi: Ecchi na Onnanoko wa Kirai... Desuka?, check the logs for more details! 
2019-12-13 14:38:41.3277 [ERROR] System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at EmbyStat.Clients.Tvdb.TvdbClient.GetEpisodes(String seriesId, CancellationToken cancellationToken) in d:\a\1\s\EmbyStat.Clients.Tvdb\TvdbClient.cs:line 66
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProgressMissingEpisodesAsync(Show show, CancellationToken cancellationToken) in d:\a\1\s\EmbyStat.Jobs\Jobs\Sync\MediaSyncJob.cs:line 330
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.GetMissingEpisodesFromTvdbAsync(Show show, CancellationToken cancellationToken) in d:\a\1\s\EmbyStat.Jobs\Jobs\Sync\MediaSyncJob.cs:line 306 System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at EmbyStat.Clients.Tvdb.TvdbClient.GetEpisodes(String seriesId, CancellationToken cancellationToken) in d:\a\1\s\EmbyStat.Clients.Tvdb\TvdbClient.cs:line 66
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProgressMissingEpisodesAsync(Show show, CancellationToken cancellationToken) in d:\a\1\s\EmbyStat.Jobs\Jobs\Sync\MediaSyncJob.cs:line 330
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.GetMissingEpisodesFromTvdbAsync(Show show, CancellationToken cancellationToken) in d:\a\1\s\EmbyStat.Jobs\Jobs\Sync\MediaSyncJob.cs:line 306
2019-12-13 14:38:41.7119 [INFO] MEDIASYNC-JOB	Processed (0/169) Ai no Katachi: Ecchi na Onnanoko wa Kirai... Desuka? 
2019-12-13 14:38:41.7433 [INFO] THETVDB-CLIENT	Call to THETVDB: https://api.thetvdb.com/series//episodes?page=1 
2019-12-13 14:38:41.8320 [ERROR] MEDIASYNC-JOB	Can't seem to process show Akiba Girls, check the logs for more details! 
2019-12-13 14:38:41.8320 [ERROR] System.ArgumentNullException: Value cannot be null.
Parameter name: source
```

**Comment by Happy2Play** [comment]
Just reported this on Emby forum.  Series without TVDBid throw this error.  But I only have one.

https://emby.media/community/index.php?/topic/56640-developing-a-standalone-embystat-server/?p=825489

**Comment by mregni** [comment]
Looks like the same exception indeed! I'll have a look when the annoying duplicate error is fixed!

**Comment by mregni** [comment]
This should be fixed in version .15 If not. Feel free to re-open!
