### ISSUE TITLE
CHECKUDPATE-JOB	No new version available 

### ISSUE THREAD

**Issue by shenniko** [mregni/EmbyStat#1034]
Hi, 

Me again.. with the same error.. ><

I'm currently running beta 13 (know 14 is out there). When i goto update says no new version, when i goto Jobs to manually run update command get the below info.

No update available

Current version: 0.2.0-beta.13

2019-12-31 14:29:57.8522 [INFO] CHECKUDPATE-JOB	Starting job 
2019-12-31 14:29:57.8718 [INFO] CHECKUDPATE-JOB	Contacting Github now to see if new version is available. 
2019-12-31 14:29:58.5166 [INFO] CHECKUDPATE-JOB	No new version available 
2019-12-31 14:29:58.5408 [INFO] CHECKUDPATE-JOB	Job finished after 1 minute. 

System Info:
Linux 5.0.0-32-generic x86_64
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco

**Comment by mregni** [comment]
That's strange indeed! Have to add some more debug info on the update job to see what happens. Maybe just a debug option would be great so I don't have to create extra builds with lot's of logging.

**Comment by Nestar47** [comment]
I had to manually update from beta 12 to 15 on Debian as well. It just showed that 12 was the current version.

**Comment by mregni** [comment]
I will push a new beta version today or tomorrow. Then the updater should see a new version. If not, feel free to respond again

**Comment by mregni** [comment]
@Nestar47, @shenniko. Took me a long time to get a new version up and running. You will need to update manually to beta.18 anyway. Can you check if the beta.18 updates to the next release next week?

**Comment by Nestar47** [comment]
Updated manually, I'll keep an eye on it

**Comment by shenniko** [comment]
Updated to v0.2.0-beta.18 manually. will wiat to see what happens with the next update :)

**Comment by mregni** [comment]
just published beta.19, let me know if your instance updates correctly

**Comment by Nestar47** [comment]
Looks like it's failing during the update process, it does see it and try it though.
https://i.imgur.com/OA2hDxc.png
https://i.imgur.com/3NluiIg.png

`2020-04-20 16:10:06.3654 [INFO] CHECKUDPATE-JOB	Starting job 
2020-04-20 16:10:06.4296 [INFO] CHECKUDPATE-JOB	Contacting Github now to see if new version is available. 
2020-04-20 16:10:07.0687 [INFO] CHECKUDPATE-JOB	New version found: v0.2.0.19 
2020-04-20 16:10:07.0687 [INFO] CHECKUDPATE-JOB	Auto update is enabled so going to update the server now! 
2020-04-20 16:10:07.4352 [INFO] --------------------------------- 
2020-04-20 16:10:07.4352 [INFO] Downloading zip file EmbyStat-debian-x64-v0.2.0-beta.19.zip 
2020-04-20 16:10:09.3776 [INFO] Connecting to wss://xxx.xxx.xxx.xxx:xxxx/embywebsocket?api_key=xxxxxxxxxxxxxx&deviceId=3687c5cb-fc38-4971-94fe-89c14a16e401 
2020-04-20 16:10:14.3776 [INFO] Connecting to wss://xxx.xxx.xxx.xxx:xxxx/embywebsocket?api_key=xxxxxxxxxxxxxx&deviceId=3687c5cb-fc38-4971-94fe-89c14a16e401 
2020-04-20 16:10:16.6414 [INFO] Downloading finished 
2020-04-20 16:10:16.6414 [INFO] --------------------------------- 
2020-04-20 16:10:16.6414 [INFO] Starting to unpack new version 
2020-04-20 16:10:19.3774 [INFO] Connecting to wss://xxx.xxx.xxx.xxx:xxxx/embywebsocket?api_key=xxxxxxxxxxxxxx&deviceId=3687c5cb-fc38-4971-94fe-89c14a16e401 
2020-04-20 16:10:21.0868 [INFO] Starting updater process. 
2020-04-20 16:10:21.0868 [INFO] /var/lib/EmbyStat 
2020-04-20 16:10:23.3974 [ERROR] Error while running job EmbyStat.Common.Exceptions.BusinessException: NOUPDATEFILE
   at EmbyStat.Services.UpdateService.<UpdateServerAsync>b__12_0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at EmbyStat.Jobs.Jobs.Updater.CheckUpdateJob.RunJobAsync()
   at EmbyStat.Jobs.Jobs.Updater.CheckUpdateJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()
2020-04-20 16:10:23.5162 [ERROR] CHECKUDPATE-JOB	Job failed, check logs for more info. 
2020-04-20 16:10:23.6771 [WARN] Failed to process the job '1bec6267-7b8b-49fb-9ff8-403bc54da205': an exception occurred. Retry attempt 2 of 2 will be performed in 00:01:00. EmbyStat.Common.Exceptions.BusinessException: NOUPDATEFILE
   at EmbyStat.Services.UpdateService.<UpdateServerAsync>b__12_0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at EmbyStat.Jobs.Jobs.Updater.CheckUpdateJob.RunJobAsync()
   at EmbyStat.Jobs.Jobs.Updater.CheckUpdateJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()
   at EmbyStat.Jobs.BaseJob.Execute()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)`

**Comment by shenniko** [comment]
same error:

2020-04-21 00:23:12.5656 [INFO] CHECKUDPATE-JOB	Starting job 
2020-04-21 00:23:12.8385 [INFO] CHECKUDPATE-JOB	Contacting Github now to see if new version is available. 
2020-04-21 00:23:13.1490 [INFO] Connecting to ws://xxx.xxx.xxx.xxx:xxxx/embywebsocket?api_key=xxxxxxxxxxxx&deviceId=38b128b9-13e1-4457-87c6-02620264301c 
2020-04-21 00:23:13.7251 [INFO] CHECKUDPATE-JOB	New version found: v0.2.0.19 
2020-04-21 00:23:13.7251 [INFO] CHECKUDPATE-JOB	Auto update is enabled so going to update the server now! 
2020-04-21 00:23:15.6392 [INFO] --------------------------------- 
2020-04-21 00:23:15.6396 [INFO] Downloading zip file EmbyStat-ubuntu-x64-v0.2.0-beta.19.zip 
2020-04-21 00:23:18.1483 [INFO] Connecting to ws://xxx.xxx.xxx.xxx:xxxx/embywebsocket?api_key=xxxxxxxxxxxx&deviceId=38b128b9-13e1-4457-87c6-02620264301c 
2020-04-21 00:23:21.9762 [INFO] Downloading finished 
2020-04-21 00:23:21.9927 [INFO] --------------------------------- 
2020-04-21 00:23:21.9927 [INFO] Starting to unpack new version 
2020-04-21 00:23:23.1487 [INFO] Connecting to ws://xxx.xxx.xxx.xxx:xxxx/embywebsocket?api_key=xxxxxxxxxxxx&deviceId=38b128b9-13e1-4457-87c6-02620264301c 
2020-04-21 00:23:28.1973 [INFO] Connecting to ws://xxx.xxx.xxx.xxx:xxxx/embywebsocket?api_key=xxxxxxxxxxxx&deviceId=38b128b9-13e1-4457-87c6-02620264301c 
2020-04-21 00:23:29.5899 [INFO] Starting updater process. 
2020-04-21 00:23:29.6296 [INFO] /home/embystat 
2020-04-21 00:23:29.7097 [ERROR] Error while running job EmbyStat.Common.Exceptions.BusinessException: NOUPDATEFILE
   at EmbyStat.Services.UpdateService.<UpdateServerAsync>b__12_0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at EmbyStat.Jobs.Jobs.Updater.CheckUpdateJob.RunJobAsync()
   at EmbyStat.Jobs.Jobs.Updater.CheckUpdateJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()
2020-04-21 00:23:33.1809 [INFO] Connecting to ws://xxx.xxx.xxx.xxx:xxxx/embywebsocket?api_key=xxxxxxxxxxxx&deviceId=38b128b9-13e1-4457-87c6-02620264301c 
2020-04-21 00:23:33.6650 [ERROR] CHECKUDPATE-JOB	Job failed, check logs for more info. 
2020-04-21 00:23:35.6275 [WARN] Failed to process the job '6899429e-03a8-43bd-b62e-ea0645923b2e': an exception occurred. Retry attempt 1 of 2 will be performed in 00:00:16. EmbyStat.Common.Exceptions.BusinessException: NOUPDATEFILE
   at EmbyStat.Services.UpdateService.<UpdateServerAsync>b__12_0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at EmbyStat.Jobs.Jobs.Updater.CheckUpdateJob.RunJobAsync()
   at EmbyStat.Jobs.Jobs.Updater.CheckUpdateJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()
   at EmbyStat.Jobs.BaseJob.Execute()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2020-04-21 00:23:38.1491 [INFO] Connecting to ws://xxx.xxx.xxx.xxx:xxxx/embywebsocket?api_key=xxxxxxxxxxxx&deviceId=38b128b9-13e1-4457-87c6-02620264301c 

Edit: Checking, it does create and download the updateFiles folder, just not sure what its trying to do after that

**Comment by mregni** [comment]
It looks like it can't find the update application itself, going to add some more debug logging for next releases. 

But I think that I made an error in my code so it's looking in the wrong directory for the update application. I'll fix this in the next release.

**Comment by shenniko** [comment]
does v0.2.0-beta.19 have this fix? As i could test (tomorrow) to see if it auto updates to 20?

Shenn

**Comment by mregni** [comment]
There is still something strange going on with the updater. I'll see that if I take the updater fix with the new version
