### ISSUE TITLE
Would you consider supporting jellyfin?

### ISSUE THREAD

**Issue by xrishox** [mregni/EmbyStat#1039]
This is a cool project, and I'm not sure if you have any interest in it or if things will diverge too much, making things difficult, but there is a huge community building up around jellyfin and it would be awesome to have this available to it!

**Comment by mregni** [comment]
Yeah, in the end, I would like to support jellyfin as well! The only problem at the moment is that I still have difficulty setting up a working version for Emby. So implementing 2 server types at the same time will be horror :) Also I'm not sure how I will implement this technically as well.

At the moment it's not working because the PING api call in Emby returns the "Emby server" string and jellyfin just returns a 200 OK. That's why jellyfin users are blocked at the end of the wizard.

It could be a good idea to start planning jellyfin implementation as well very soon (so I know the basic statistics work on Emby and jellyfin) but I will need to setup a test server at home first as well.

**Comment by samuel9554** [comment]
+1

**Comment by mregni** [comment]
Started implementing Jellyfin support and I got a long way already. But it seems that Jellyfin is not supporting ItemQueries without user id. So I have to wait for a fix on JF before I can release the Jellyfin support.

https://github.com/jellyfin/jellyfin/issues/2246

**Comment by mregni** [comment]
Seems like everything is working now for Jellyfin. I do need to wait for the API update on the Jellyfin server before I can release this. Next step is to make all "Emby" constants dynamic (Emby or Jellyfin)

**Comment by samuel9554** [comment]
Can we test it before you release?
I'm running Jellyfin 10.4.3.

**Comment by mregni** [comment]
Sure, but at the moment it's not even testable. The API call /Items needs a UserId when called but on Emby you don't need a user for that. So, they have to update the implementation of the call before I can give you guys a nightly build to test :)

I'll keep you posted when I have a working version!

**Comment by xrishox** [comment]
Wow thank you so much for being so open and friendly about this. Hopefully whatever it is you need makes it into the next release of jellyfin. Seems like they are open to it too.

**Comment by mregni** [comment]
Glad to help and add Jellyfin support asap! Currently, I created a PR but it will take some time because we need to figure out a way that a normal user can't just query all data by removing his userid :)

**Comment by samuel9554** [comment]
> 
> 
> Glad to help and add Jellyfin support asap! Currently, I created a PR but it will take some time because we need to figure out a way that a normal user can't just query all data by removing his userid :)

In my opinion we should use the user ID that create the API key. Because if the user is able to create a API Key he is also able to manage and see all the library anyway...

**Comment by mregni** [comment]
True, but I have no idea in EmbyStat what user created the API key. Also, this works in Emby so not sure how they check if the authenticated token is from a user or an API key

**Comment by samuel9554** [comment]
Do you think you could add a input text during the configuration at the end for input user ID? If it detect is a Jellyfin server it will ask for a user ID.

**Comment by mregni** [comment]
I can add a dropdown where Jellyfin users need to select the user they want to use to fetch data. Only problem is that when certain libraries are not visible to that user they also will not be visible in EmbyStat. 

But we maybe can make an assumption here that the user will always select an admin account and that admins always have access to all libraries.

**Comment by samuel9554** [comment]
> But we maybe can make an assumption here that the user will always select an admin account and that admins always have access to all libraries.

I think it's safe to assume that.

**Comment by CyberPoison** [comment]
+1

**Comment by spupuz** [comment]
Does embystat works actually with jellyfin or still trying to make it work?

**Comment by mregni** [comment]
Going to release a new beta with support for Jellyfin. Keep an eye out for a new version soon :) Let's hope it works! Keep in mind that EmbyStat is still in a very unstable situation and should only be used for testing at the moment.

**Comment by samuel9554** [comment]
When is out please notify here!!! I will test for sure.
Also will you release a Docker container?

**Comment by spupuz** [comment]
i also need a docker container

**Comment by bluasoar** [comment]
@mregni Just wondering how Jellyfin support has been going? I have the latest Docker running and am having no luck so I assume it's still in the works? Thanks for all your hard work. I appreciate it.

**Comment by mregni** [comment]
Hey guys, I just released a new beta version 0.2.0-beta.17 that should support jellyfin. Hope it works :)

If any issues are found please let me know but keep in mind this is still all in beta phase, don't keep it running for a long time :)

**Comment by spupuz** [comment]
There is also an updated docker image?

Il Mar 7 Apr 2020, 18:44 Mikhaël Regni <notifications@github.com> ha
scritto:

**Comment by mregni** [comment]
Yes, on every beta release the beta docker containers are also updated. Just use the :beta tag

**Comment by bluasoar** [comment]
I am trying to run the beta tag on unRAID but am getting an error "Did you mean to run dotnet SDK commands? Please install dotnet SDK from [link]" I have seen some other people reporting the same issue but with little info to go off of.

**Comment by mregni** [comment]
unRAID does indeed some strange stuff with it, you can find install steps here: https://emby.media/community/index.php?/topic/56640-developing-a-standalone-embystat-server/?p=773230 

If that works let me know so I can add it to the Wiki!
I also added an unRAID config xml to the repo here: https://github.com/mregni/EmbyStat/tree/develop/Templates/unraid

**Comment by spupuz** [comment]
not working uping/embystat:beta

root@openmediavault:~# docker create \
>   --name=embystat \
>   -e PUID=1000 \
>   -e PGID=1000 \
>   -e TZ=Europe/London \
>   -p 6555:6555 \
>   -v/srv/dev-disk-by-label-Data/DockerConfig/embystat/config:/config \
>   --restart unless-stopped \
>   upng/embystat:beta
Unable to find image 'upng/embystat:beta' locally
Error response from daemon: pull access denied for upng/embystat,
repository does not exist or may require 'docker login': denied: requested
access to the resource is denied

what i have to do?

Belloni Alessandro
http://www.linkedin.com/in/bellonialessandro
---------------------------------------------------------------


Il giorno mar 7 apr 2020 alle ore 21:32 Mikhaël Regni <
notifications@github.com> ha scritto:

**Comment by spupuz** [comment]
ok i have seen the syntax error.

Belloni Alessandro
http://www.linkedin.com/in/bellonialessandro
---------------------------------------------------------------


Il giorno mar 7 apr 2020 alle ore 21:37 Alessandro Belloni <spupuz@gmail.com>
ha scritto:

**Comment by mregni** [comment]
Hehehe, yeah it's ´uping/embystat:beta´. But there is a problem with the paths at the moment so I will create new release tonight.

**Comment by spupuz** [comment]
i also have the error:

Did you mean to run dotnet SDK commands? Please install dotnet SDK from:


  https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409


Belloni Alessandro
http://www.linkedin.com/in/bellonialessandro
---------------------------------------------------------------


Il giorno mar 7 apr 2020 alle ore 21:52 Mikhaël Regni <
notifications@github.com> ha scritto:

**Comment by bluasoar** [comment]
> 
> 
> unRAID does indeed some strange stuff with it, you can find install steps here: https://emby.media/community/index.php?/topic/56640-developing-a-standalone-embystat-server/?p=773230
> 
> If that works let me know so I can add it to the Wiki!
> I also added an unRAID config xml to the repo here: https://github.com/mregni/EmbyStat/tree/develop/Templates/unraid

I tried the steps provided deleted my old config redownloaded added the nlog.config folder to appdata and I am still getting the same error "Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409"

**Comment by mregni** [comment]
mmm, that's because the docker containers are corrupted at the moment because of a wrong path configured. "Did you mean to run dotnet SDK commands?" happens when embystat starting with strange parameters. This is because the corrupted images.

**Comment by spupuz** [comment]
ok let us know when correct image is available

**Comment by mregni** [comment]
Trying to rebuild but looks like NuGet package manager is unreachable from the Azure DevOps services at this moment. Will try tomorrow morning again. I'lll keep you all updated!

**Comment by mregni** [comment]
Containers are updated, hope it works now :)

**Comment by spupuz** [comment]
ok started and configured but the media sync it is not working.

`2020-04-08 11:43:59.0486 [INFO] SYSTEM	Booting up server on port 6555 
2020-04-08 11:44:00.4750 [INFO] Starting Hangfire Server using job storage: 'Hangfire.MemoryStorage.MemoryStorage' 
2020-04-08 11:44:00.4805 [INFO] Using the following options for Hangfire Server:
    Worker count: 1
    Listening queues: 'main'
    Shutdown timeout: 1.00:00:00
    Schedule polling interval: 00:00:05 
2020-04-08 11:44:00.7264 [INFO] Server main server:1:44697e41 successfully announced in 214.9319 ms 
2020-04-08 11:44:00.7353 [INFO] Server main server:1:44697e41 is starting the registered dispatchers: ServerWatchdog, ServerJobCancellationWatcher, ExpirationManager, CountersAggregator, Worker, DelayedJobScheduler, RecurringJobScheduler... 
2020-04-08 11:44:00.7782 [INFO] Server main server:1:44697e41 all the dispatchers started 
2020-04-08 11:44:27.0562 [INFO] SERVER-API	jellyfin server found at: 172.17.0.5 
2020-04-08 11:45:10.6953 [INFO] Connecting to wss://xxx.xxx.xxx.xxx:xxxx/embywebsocket?api_key=xxxxxxxxxxxxxx&deviceId=2abd8caa-ffdf-4c36-92e9-dce5a46b58e3 
2020-04-08 11:45:15.6922 [INFO] Connecting to wss://xxx.xxx.xxx.xxx:xxxx/embywebsocket?api_key=xxxxxxxxxxxxxx&deviceId=2abd8caa-ffdf-4c36-92e9-dce5a46b58e3 
2020-04-08 11:45:16.0956 [INFO] SMALLEMBYSYNC-JOB	Starting job 
2020-04-08 11:45:16.2790 [INFO] SMALLEMBYSYNC-JOB	Server info downloaded 
2020-04-08 11:45:16.4306 [INFO] SMALLEMBYSYNC-JOB	Server plugins downloaded 
2020-04-08 11:45:16.6946 [INFO] SMALLEMBYSYNC-JOB	Server users downloaded 
2020-04-08 11:45:17.8280 [INFO] SMALLEMBYSYNC-JOB	Server devices downloaded 
2020-04-08 11:45:18.0891 [INFO] SMALLEMBYSYNC-JOB	Job finished after 1 minute. 
2020-04-08 11:45:18.5938 [INFO] MEDIASYNC-JOB	Starting job 
2020-04-08 11:45:18.7084 [INFO] MEDIASYNC-JOB	First delete all existing media and root media libraries from database so we have a clean start. 
2020-04-08 11:45:18.7110 [INFO] MEDIASYNC-JOB	Asking MediaServer for all root folders 
2020-04-08 11:45:18.8380 [INFO] MEDIASYNC-JOB	Found 6 root items, getting ready for processing 
2020-04-08 11:45:18.8452 [INFO] MEDIASYNC-JOB	Lets start processing movies 
2020-04-08 11:45:18.9566 [ERROR] Error while running job System.NullReferenceException: Object reference not set to an instance of an object.
   at EmbyStat.Clients.Base.Http.BaseHttpClient.GetMovieCount(String parentId)
   at EmbyStat.Clients.Jellyfin.Http.JellyfinHttpClient.EmbyStat.Clients.Base.Http.IHttpClient.GetMovieCount(String parentId)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessMoviesAsync(IReadOnlyList`1 libraries, CancellationToken cancellationToken)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()
2020-04-08 11:45:19.0125 [ERROR] MEDIASYNC-JOB	Job failed, check logs for more info. 
2020-04-08 11:45:20.1230 [WARN] Failed to process the job 'd1fe433c-87bd-4440-ac94-4c7d6c8a4e90': an exception occurred. Retry attempt 1 of 2 will be performed in 00:00:36. System.NullReferenceException: Object reference not set to an instance of an object.
   at EmbyStat.Clients.Base.Http.BaseHttpClient.GetMovieCount(String parentId)
   at EmbyStat.Clients.Jellyfin.Http.JellyfinHttpClient.EmbyStat.Clients.Base.Http.IHttpClient.GetMovieCount(String parentId)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessMoviesAsync(IReadOnlyList`1 libraries, CancellationToken cancellationToken)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()
   at EmbyStat.Jobs.BaseJob.Execute()
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
2020-04-08 11:45:20.7157 [INFO] Connecting to wss://xxx.xxx.xxx.xxx:xxxx/embywebsocket?api_key=xxxxxxxxxxxxxx&deviceId=2abd8caa-ffdf-4c36-92e9-dce5a46b58e3 
2020-04-08 11:45:25.6871 [INFO] Connecting to wss://xxx.xxx.xxx.xxx:xxxx/embywebsocket?api_key=xxxxxxxxxxxxxx&deviceId=2abd8caa-ffdf-4c36-92e9-dce5a46b58e3 
2020-04-08 11:45:30.6921 [INFO] Connecting to wss://xxx.xxx.xxx.xxx:xxxx/embywebsocket?api_key=xxxxxxxxxxxxxx&deviceId=2abd8caa-ffdf-4c36-92e9-dce5a46b58e3 
2020-04-08 11:45:35.6872 [INFO] Connecting to wss://xxx.xxx.xxx.xxx:xxxx/embywebsocket?api_key=xxxxxxxxxxxxxx&deviceId=2abd8caa-ffdf-4c36-92e9-dce5a46b58e3 
2020-04-08 11:45:35.8272 [INFO] MEDIASYNC-JOB	Starting job 
2020-04-08 11:45:35.9284 [INFO] MEDIASYNC-JOB	First delete all existing media and root media libraries from database so we have a clean start. 
2020-04-08 11:45:35.9284 [INFO] MEDIASYNC-JOB	Asking MediaServer for all root folders 
2020-04-08 11:45:35.9773 [INFO] MEDIASYNC-JOB	Found 6 root items, getting ready for processing 
2020-04-08 11:45:35.9790 [INFO] MEDIASYNC-JOB	Lets start processing movies 
2020-04-08 11:45:36.0092 [ERROR] Error while running job System.NullReferenceException: Object reference not set to an instance of an object.
   at EmbyStat.Clients.Base.Http.BaseHttpClient.GetMovieCount(String parentId)
   at EmbyStat.Clients.Jellyfin.Http.JellyfinHttpClient.EmbyStat.Clients.Base.Http.IHttpClient.GetMovieCount(String parentId)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessMoviesAsync(IReadOnlyList`1 libraries, CancellationToken cancellationToken)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()
2020-04-08 11:45:36.0432 [ERROR] MEDIASYNC-JOB	Job failed, check logs for more info. 
2020-04-08 11:45:36.7765 [WARN] Failed to process the job '14dc8978-c7bb-4d65-80d9-61d5de6c51cd': an exception occurred. Retry attempt 1 of 2 will be performed in 00:00:44. System.NullReferenceException: Object reference not set to an instance of an object.
   at EmbyStat.Clients.Base.Http.BaseHttpClient.GetMovieCount(String parentId)
   at EmbyStat.Clients.Jellyfin.Http.JellyfinHttpClient.EmbyStat.Clients.Base.Http.IHttpClient.GetMovieCount(String parentId)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessMoviesAsync(IReadOnlyList`1 libraries, CancellationToken cancellationToken)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()
   at EmbyStat.Jobs.BaseJob.Execute()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2020-04-08 11:45:40.6876 [INFO] Connecting to wss://xxx.xxx.xxx.xxx:xxxx/embywebsocket?api_key=xxxxxxxxxxxxxx&deviceId=2abd8caa-ffdf-4c36-92e9-dce5a46b58e3 
2020-04-08 11:45:45.6866 [INFO] Connecting to wss://xxx.xxx.xxx.xxx:xxxx/embywebsocket?api_key=xxxxxxxxxxxxxx&deviceId=2abd8caa-ffdf-4c36-92e9-dce5a46b58e3 
2020-04-08 11:45:50.6895 [INFO] Connecting to wss://xxx.xxx.xxx.xxx:xxxx/embywebsocket?api_key=xxxxxxxxxxxxxx&deviceId=2abd8caa-ffdf-4c36-92e9-dce5a46b58e3 
2020-04-08 11:45:55.7509 [INFO] Connecting to wss://xxx.xxx.xxx.xxx:xxxx/embywebsocket?api_key=xxxxxxxxxxxxxx&deviceId=2abd8caa-ffdf-4c36-92e9-dce5a46b58e3 
2020-04-08 11:46:00.6894 [INFO] Connecting to wss://xxx.xxx.xxx.xxx:xxxx/embywebsocket?api_key=xxxxxxxxxxxxxx&deviceId=2abd8caa-ffdf-4c36-92e9-dce5a46b58e3 
2020-04-08 11:46:05.6876 [INFO] Connecting to wss://xxx.xxx.xxx.xxx:xxxx/embywebsocket?api_key=xxxxxxxxxxxxxx&deviceId=2abd8caa-ffdf-4c36-92e9-dce5a46b58e3 
2020-04-08 11:46:06.8518 [INFO] MEDIASYNC-JOB	Starting job 
2020-04-08 11:46:06.9256 [INFO] MEDIASYNC-JOB	First delete all existing media and root media libraries from database so we have a clean start. 
2020-04-08 11:46:06.9275 [INFO] MEDIASYNC-JOB	Asking MediaServer for all root folders 
2020-04-08 11:46:06.9672 [INFO] MEDIASYNC-JOB	Found 6 root items, getting ready for processing 
2020-04-08 11:46:06.9672 [INFO] MEDIASYNC-JOB	Lets start processing movies 
2020-04-08 11:46:07.0123 [ERROR] Error while running job System.NullReferenceException: Object reference not set to an instance of an object.
   at EmbyStat.Clients.Base.Http.BaseHttpClient.GetMovieCount(String parentId)
   at EmbyStat.Clients.Jellyfin.Http.JellyfinHttpClient.EmbyStat.Clients.Base.Http.IHttpClient.GetMovieCount(String parentId)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessMoviesAsync(IReadOnlyList`1 libraries, CancellationToken cancellationToken)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()
2020-04-08 11:46:07.0813 [ERROR] MEDIASYNC-JOB	Job failed, check logs for more info. 
2020-04-08 11:46:07.6671 [WARN] Failed to process the job 'd1fe433c-87bd-4440-ac94-4c7d6c8a4e90': an exception occurred. Retry attempt 2 of 2 will be performed in 00:00:38. System.NullReferenceException: Object reference not set to an instance of an object.
   at EmbyStat.Clients.Base.Http.BaseHttpClient.GetMovieCount(String parentId)
   at EmbyStat.Clients.Jellyfin.Http.JellyfinHttpClient.EmbyStat.Clients.Base.Http.IHttpClient.GetMovieCount(String parentId)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessMoviesAsync(IReadOnlyList`1 libraries, CancellationToken cancellationToken)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()
   at EmbyStat.Jobs.BaseJob.Execute()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2020-04-08 11:46:07.7107 [INFO] MEDIASYNC-JOB	Starting job 
2020-04-08 11:46:07.7718 [INFO] MEDIASYNC-JOB	First delete all existing media and root media libraries from database so we have a clean start. 
2020-04-08 11:46:07.7718 [INFO] MEDIASYNC-JOB	Asking MediaServer for all root folders 
2020-04-08 11:46:07.8243 [INFO] MEDIASYNC-JOB	Found 6 root items, getting ready for processing 
2020-04-08 11:46:07.8243 [INFO] MEDIASYNC-JOB	Lets start processing movies 
2020-04-08 11:46:07.8619 [ERROR] Error while running job System.NullReferenceException: Object reference not set to an instance of an object.
   at EmbyStat.Clients.Base.Http.BaseHttpClient.GetMovieCount(String parentId)
   at EmbyStat.Clients.Jellyfin.Http.JellyfinHttpClient.EmbyStat.Clients.Base.Http.IHttpClient.GetMovieCount(String parentId)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessMoviesAsync(IReadOnlyList`1 libraries, CancellationToken cancellationToken)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()
2020-04-08 11:46:07.8953 [ERROR] MEDIASYNC-JOB	Job failed, check logs for more info. 
2020-04-08 11:46:08.6235 [WARN] Failed to process the job '0f980538-c525-4305-bb8c-0c0b56b0bd69': an exception occurred. Retry attempt 1 of 2 will be performed in 00:00:17. System.NullReferenceException: Object reference not set to an instance of an object.
   at EmbyStat.Clients.Base.Http.BaseHttpClient.GetMovieCount(String parentId)
   at EmbyStat.Clients.Jellyfin.Http.JellyfinHttpClient.EmbyStat.Clients.Base.Http.IHttpClient.GetMovieCount(String parentId)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessMoviesAsync(IReadOnlyList`1 libraries, CancellationToken cancellationToken)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()
   at EmbyStat.Jobs.BaseJob.Execute()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2020-04-08 11:46:10.6897 [INFO] Connecting to wss://xxx.xxx.xxx.xxx:xxxx/embywebsocket?api_key=xxxxxxxxxxxxxx&deviceId=2abd8caa-ffdf-4c36-92e9-dce5a46b58e3 
2020-04-08 11:46:15.6891 [INFO] Connecting to wss://xxx.xxx.xxx.xxx:xxxx/embywebsocket?api_key=xxxxxxxxxxxxxx&deviceId=2abd8caa-ffdf-4c36-92e9-dce5a46b58e3 
`

**Comment by bluasoar** [comment]
Also getting the same error as @spupuz 

Logs - https://pastebin.com/RTSSA9sm

**Comment by mregni** [comment]
Going to close this issue because the support is added in the beta. If you find anything that's not working for Jellyfin, please create a new issue for it.

@bluasoar and @spupuz, I created a new issue for your problem here => #1155
