### ISSUE TITLE
No movie data

### ISSUE THREAD

**Issue by fjruhl** [mregni/EmbyStat#1041]
# Bug report

**Describe the bug
program crashes and when click on movies or shows  in lower right corner
unhandled backend exception
**To Reproduce**
Steps to reproduce the behavior: just click on tv shows and back to movies

**Expected behavior**
no errors

**Screenshots**
![embystat error](https://user-images.githubusercontent.com/16024335/71743920-be59fe00-2e33-11ea-923e-5c6bee16a317.JPG)

**System (please complete the following information):**

- OS: [e.g. Windows 10, chrome and unraid server

**Additional context**

**Comment by Happy2Play** [comment]
Sorry I don't follow.  What are you clicking on as I don't see "..." in EmbyStats that you are referencing.

**Comment by mregni** [comment]
Can you supply me with your log file? When there is an unhandled exception the stack trace will be in the log files :)

**Comment by fjruhl** [comment]
sorry it took so long,  i just got a can't update server in the update tab.
does this update from the docker update all setting.

 Updates are disabled for this server and will probably be updated by an
external service. If this is a mistake don't start the server with the
--no-updates option.

**Comment by mregni** [comment]
That's because you are using the docker image from the linuxserver.io guys :) They always run EmbyStat with the --no-updates flag because they want to keep the update flow in control. I just checked and they updated their image to beta.15 so you should be able to update your container as well to beta.15

**Comment by aptalca** [comment]
I'm seeing similar issues as well.

I think it's related to the media synchronisation job failing.

Media sync successfully processes first the movies and then the shows. But right after it outputs `Removing shows that are no longer present on your server (if any)`, it quits with the following error from the log:
```
2020-01-07 18:27:09.8074 [ERROR] Error while running job System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.String'.
   at lambda_method(Closure , Object , Object )
   at LiteDB.BsonMapper.DeserializeObject(Type type, Object obj, BsonDocument value)
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.BsonMapper.DeserializeList(Type type, BsonArray value)
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.BsonMapper.<>c__DisplayClass45_0.<RegisterDbRefList>b__1(BsonValue bson, BsonMapper m)
   at LiteDB.BsonMapper.DeserializeObject(Type type, Object obj, BsonDocument value)
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.BsonMapper.ToObject[T](BsonDocument doc)
   at LiteDB.LiteCollection`1.Find(Query query, Int32 skip, Int32 limit)+MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EmbyStat.Repositories.ShowRepository.<>c__DisplayClass2_0.<RemoveShowsThatAreNotUpdated>b__0() in d:\a\1\s\EmbyStat.Repositories\ShowRepository.cs:line 40
   at EmbyStat.Repositories.BaseRepository.ExecuteQuery(Action query) in d:\a\1\s\EmbyStat.Repositories\BaseRepository.cs:line 29
   at EmbyStat.Repositories.ShowRepository.RemoveShowsThatAreNotUpdated(DateTime startTime) in d:\a\1\s\EmbyStat.Repositories\ShowRepository.cs:line 49
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessShowsAsync(IEnumerable`1 libraries, CancellationToken cancellationToken) in d:\a\1\s\EmbyStat.Jobs\Jobs\Sync\MediaSyncJob.cs:line 206
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync() in d:\a\1\s\EmbyStat.Jobs\Jobs\Sync\MediaSyncJob.cs:line 85
   at EmbyStat.Jobs.BaseJob.Execute() in d:\a\1\s\EmbyStat.Jobs\BaseJob.cs:line 54
2020-01-07 18:27:09.8283 [ERROR] MEDIASYNC-JOB	Job failed, check logs for more info. 
2020-01-07 18:27:10.0211 [WARN] Failed to process the job '4f8c330b-435f-4637-8701-3779494c743f': an exception occurred. Retry attempt 2 of 2 will be performed in 00:01:10. System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.String'.
   at lambda_method(Closure , Object , Object )
   at LiteDB.BsonMapper.DeserializeObject(Type type, Object obj, BsonDocument value)
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.BsonMapper.DeserializeList(Type type, BsonArray value)
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.BsonMapper.<>c__DisplayClass45_0.<RegisterDbRefList>b__1(BsonValue bson, BsonMapper m)
   at LiteDB.BsonMapper.DeserializeObject(Type type, Object obj, BsonDocument value)
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.BsonMapper.ToObject[T](BsonDocument doc)
   at LiteDB.LiteCollection`1.Find(Query query, Int32 skip, Int32 limit)+MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EmbyStat.Repositories.ShowRepository.<>c__DisplayClass2_0.<RemoveShowsThatAreNotUpdated>b__0() in d:\a\1\s\EmbyStat.Repositories\ShowRepository.cs:line 40
   at EmbyStat.Repositories.BaseRepository.ExecuteQuery(Action query) in d:\a\1\s\EmbyStat.Repositories\BaseRepository.cs:line 29
   at EmbyStat.Repositories.ShowRepository.RemoveShowsThatAreNotUpdated(DateTime startTime) in d:\a\1\s\EmbyStat.Repositories\ShowRepository.cs:line 49
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessShowsAsync(IEnumerable`1 libraries, CancellationToken cancellationToken) in d:\a\1\s\EmbyStat.Jobs\Jobs\Sync\MediaSyncJob.cs:line 206
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync() in d:\a\1\s\EmbyStat.Jobs\Jobs\Sync\MediaSyncJob.cs:line 85
   at EmbyStat.Jobs.BaseJob.Execute() in d:\a\1\s\EmbyStat.Jobs\BaseJob.cs:line 54
   at EmbyStat.Jobs.BaseJob.Execute() in d:\a\1\s\EmbyStat.Jobs\BaseJob.cs:line 66
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

It retries a few times, during which time the Movies tab is inaccessible (displays the error Unhandled backend exception). After it finally finishes, it displays the Movies tab, but the Most Featured Actor, Director, Writer and Actor per Genre are blank. The general Movie info is displayed fine.

TV Shows on the other hand keeps giving the `Unhandled backend exception` error as in the screenshot and does not display any info.

I'm also on beta.15 (docker)

Thanks

EDIT: I nuked the database and all data and started from scratch and everything's good. Perhaps something broke during update of either embystat or emby

**Comment by aptalca** [comment]
It seems when the media sync job fails, the statistics calculation continues in the background, but the webgui is unaware. Instead of displaying the notice about ongoing sync, it tries to open the Movies/TV tabs and gets the backend error

**Comment by Happy2Play** [comment]
As mentioned elsewhere the update had database changes that require a clean install.  At least for users that experiencing errors.

**Comment by aptalca** [comment]
Thanks, simple enough. It only takes a couple of minutes to set it up.

**Comment by mregni** [comment]
Sorry, I didn't mention it on the release post that you needed a clean install. 

The issue you mentioned before about the statistics calculation continues even if the job fails worries me a bit. The calculation is just the last step of the sync job BUT if the user opens the Movies or Shows tab and EmbyStat can't find any valid statistics it will calculate them while loading the Movies page. So maybe that's the exception you are seeing. Could you send me a log file if that happens again?
