### ISSUE TITLE
Meida sync failed 

### ISSUE THREAD

**Issue by Kodiak437** [mregni/EmbyStat#1121]
Hello,

Just did a fresh install on deb 10.  Getting the below error.  Any ideas?  Thanks

2020-03-24 15:21:35.0830 [INFO] MEDIASYNC-JOB	Starting job 
2020-03-24 15:21:35.1199 [INFO] MEDIASYNC-JOB	First delete all existing media and root media libraries from database so we have a clean start. 
2020-03-24 15:21:35.1199 [INFO] MEDIASYNC-JOB	Asking Emby for all root folders 
2020-03-24 15:21:35.1473 [INFO] MEDIASYNC-JOB	Found 10 root items, getting ready for processing 
2020-03-24 15:21:35.1473 [INFO] MEDIASYNC-JOB	Lets start processing movies 
2020-03-24 15:21:35.1599 [ERROR] Error while running job System.Collections.Generic.KeyNotFoundException: The given key '47' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at LiteDB.IndexService.Delete(CollectionIndex index, PageAddress nodeAddress)
   at LiteDB.LiteEngine.<>c__DisplayClass8_0.<Delete>b__0(CollectionPage col)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at EmbyStat.Repositories.MovieRepository.<RemoveMovies>b__15_0() in d:\a\1\s\EmbyStat.Repositories\MovieRepository.cs:line 287
   at EmbyStat.Repositories.BaseRepository.ExecuteQuery(Action query) in d:\a\1\s\EmbyStat.Repositories\BaseRepository.cs:line 29
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessMoviesAsync(IReadOnlyList`1 libraries, CancellationToken cancellationToken) in d:\a\1\s\EmbyStat.Jobs\Jobs\Sync\MediaSyncJob.cs:line 98
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync() in d:\a\1\s\EmbyStat.Jobs\Jobs\Sync\MediaSyncJob.cs:line 82
   at EmbyStat.Jobs.BaseJob.Execute() in d:\a\1\s\EmbyStat.Jobs\BaseJob.cs:line 54
2020-03-24 15:21:35.1900 [ERROR] MEDIASYNC-JOB	Job failed, check logs for more info. 
2020-03-24 15:21:35.6786 [WARN] Failed to process the job '59f6bee5-2b0d-4aac-922d-9894fd7c39fd': an exception occurred. Retry attempt 1 of 2 will be performed in 00:00:39. System.Collections.Generic.KeyNotFoundException: The given key '47' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at LiteDB.IndexService.Delete(CollectionIndex index, PageAddress nodeAddress)
   at LiteDB.LiteEngine.<>c__DisplayClass8_0.<Delete>b__0(CollectionPage col)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at EmbyStat.Repositories.MovieRepository.<RemoveMovies>b__15_0() in d:\a\1\s\EmbyStat.Repositories\MovieRepository.cs:line 287
   at EmbyStat.Repositories.BaseRepository.ExecuteQuery(Action query) in d:\a\1\s\EmbyStat.Repositories\BaseRepository.cs:line 29
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessMoviesAsync(IReadOnlyList`1 libraries, CancellationToken cancellationToken) in d:\a\1\s\EmbyStat.Jobs\Jobs\Sync\MediaSyncJob.cs:line 98
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync() in d:\a\1\s\EmbyStat.Jobs\Jobs\Sync\MediaSyncJob.cs:line 82
   at EmbyStat.Jobs.BaseJob.Execute() in d:\a\1\s\EmbyStat.Jobs\BaseJob.cs:line 54
   at EmbyStat.Jobs.BaseJob.Execute() in d:\a\1\s\EmbyStat.Jobs\BaseJob.cs:line 66
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2020-03-24 15:22:20.7759 [INFO] MEDIASYNC-JOB	Starting job 
2020-03-24 15:22:20.8052 [ERROR] Error in event handler LiteDB.LiteException: Your datafile did not terminate properly during the writing process. Reopen the file
   at LiteDB.LockService.DetectDatabaseChanges()
   at LiteDB.LockService.Read()
   at LiteDB.LiteEngine.Find(String collection, Query query, Int32 skip, Int32 limit)+MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at LiteDB.LiteEngine.FindById(String collection, BsonValue id)
   at LiteDB.LiteEngine.Find(String collection, Query query, String[] includes, Int32 skip, Int32 limit)+MoveNext()
   at LiteDB.LiteCollection`1.Find(Query query, Int32 skip, Int32 limit)+MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at EmbyStat.Repositories.SessionRepository.<>c__DisplayClass3_0.<GetSessionById>b__0() in d:\a\1\s\EmbyStat.Repositories\SessionRepository.cs:line 48
   at EmbyStat.Repositories.BaseRepository.ExecuteQuery[T1](Func`1 query) in d:\a\1\s\EmbyStat.Repositories\BaseRepository.cs:line 21
   at EmbyStat.Services.SessionService.ProcessSessions(List`1 sessions) in d:\a\1\s\EmbyStat.Services\SessionService.cs:line 42
   at EmbyStat.Services.WebSocketService.WebSocketApiSessionsUpdated(Object sender, GenericEventArgs`1 e) in d:\a\1\s\EmbyStat.Services\WebSocketService.cs:line 107
   at EmbyStat.Clients.Emby.WebSocket.WebSocketApi.FireEvent[T](EventHandler`1 handler, Object sender, T args) in d:\a\1\s\EmbyStat.Clients.Emby.WebSocket\WebSocketApi.cs:line 212

**Comment by mregni** [comment]
@Kodiak437, can you do a reinstall with the new version (beta.18)? I updated to LiteDB V5 and it's possible your problem is fixed with the update as well.
