### ISSUE TITLE
Container doesn't start after upgrade to beta18

### ISSUE THREAD

**Issue by deeprain279** [mregni/EmbyStat#1152]
# Bug report

**Describe the bug**
After upgrading the Docker image from 0.2.0 Beta 15 to Beta 18, the container (Ubuntu) no longer starts.
Restarting or stopping and starting the container with docker-compose does not help.
I use the container from linuxserver/embystat:latest

**System (please complete the following information):**
- OS: linuxserver/embystat:latest
-- EBIAN_FRONTEND=noninteractive OVERLAY_ARCH=amd64 OVERLAY_VERSION=v1.22.0.0 VERSION=76cfc77b-ls35 /bin/sh -c echo "**** Ripped from Ubuntu Docker Logic ****

**Log**
Apr 10 11:01:05 embyStat [cont-init.d] executing container initialization scripts...
Apr 10 11:01:05 embyStat [cont-init.d] 01-envfile: executing... 
Apr 10 11:01:05 embyStat [cont-init.d] 01-envfile: exited 0.
Apr 10 11:01:05 embyStat [cont-init.d] 10-adduser: executing... 
Apr 10 11:01:05 embyStat usermod: no changes
Apr 10 11:01:05 embyStat 
Apr 10 11:01:05 embyStat -------------------------------------
Apr 10 11:01:05 embyStat           _         ()
Apr 10 11:01:05 embyStat          | |  ___   _    __
Apr 10 11:01:05 embyStat          | | / __| | |  /  \ 
Apr 10 11:01:05 embyStat          | | \__ \ | | | () |
Apr 10 11:01:05 embyStat          |_| |___/ |_|  \__/
Apr 10 11:01:05 embyStat 
Apr 10 11:01:05 embyStat 
Apr 10 11:01:05 embyStat Brought to you by linuxserver.io
Apr 10 11:01:05 embyStat -------------------------------------
Apr 10 11:01:05 embyStat 
Apr 10 11:01:05 embyStat To support LSIO projects visit:
Apr 10 11:01:05 embyStat https://www.linuxserver.io/donate/
Apr 10 11:01:05 embyStat -------------------------------------
Apr 10 11:01:05 embyStat GID/UID
Apr 10 11:01:05 embyStat -------------------------------------
Apr 10 11:01:05 embyStat 
Apr 10 11:01:05 embyStat User uid:    1000
Apr 10 11:01:05 embyStat User gid:    100
Apr 10 11:01:05 embyStat -------------------------------------
Apr 10 11:01:05 embyStat 
Apr 10 11:01:06 embyStat [cont-init.d] 10-adduser: exited 0.
Apr 10 11:01:06 embyStat [cont-init.d] 30-config: executing... 
Apr 10 11:01:06 embyStat [cont-init.d] 30-config: exited 0.
Apr 10 11:01:06 embyStat [cont-init.d] 99-custom-scripts: executing... 
Apr 10 11:01:06 embyStat [custom-init] no custom files found exiting...
Apr 10 11:01:06 embyStat [cont-init.d] 99-custom-scripts: exited 0.
Apr 10 11:01:06 embyStat [cont-init.d] done.
Apr 10 11:01:06 embyStat [services.d] starting services
Apr 10 11:01:06 embyStat [services.d] done.
Apr 10 11:01:07 embyStat File is not a valid LiteDB database format or contains a invalid password.
Apr 10 11:01:07 embyStat SYSTEM#011Server shutdown
Apr 10 11:01:07 embyStat File is not a valid LiteDB database format or contains a invalid password.
Apr 10 11:01:07 embyStat SYSTEM#011Server shutdown
Apr 10 11:01:08 embyStat File is not a valid LiteDB database format or contains a invalid password.
Apr 10 11:01:08 embyStat SYSTEM#011Server shutdown
Apr 10 11:01:10 embyStat File is not a valid LiteDB database format or contains a invalid password.
Apr 10 11:01:10 embyStat SYSTEM#011Server shutdown
Apr 10 11:01:11 embyStat File is not a valid LiteDB database format or contains a invalid password.
Apr 10 11:01:11 embyStat SYSTEM#011Server shutdown

**Comment by deeprain279** [comment]
embyStat log:
2020-04-10 11:01:10.7331 [INFO] SYSTEM  Booting up server on port 6555 
2020-04-10 11:01:11.0018 [FATAL] LiteDB.LiteException: File is not a valid LiteDB database format or contains a invalid password.
   at LiteDB.Engine.HeaderPage.LoadPage()
   at LiteDB.Engine.HeaderPage..ctor(PageBuffer buffer)
   at LiteDB.Engine.LiteEngine..ctor(EngineSettings settings)
   at LiteDB.SharedEngine.OpenDatabase()
   at LiteDB.SharedEngine.EnsureIndex(String collection, String name, BsonExpression expression, Boolean unique)
   at LiteDB.LiteCollection`1.EnsureIndex(String name, BsonExpression expression, Boolean unique)
   at LiteDB.LiteCollection`1.EnsureIndex(BsonExpression expression, Boolean unique)
   at LiteDB.LiteCollection`1.EnsureIndex[K](Expression`1 keySelector, Boolean unique)
   at EmbyStat.Repositories.DatabaseInitializer.CreateIndexes()
   at EmbyStat.Web.Program.SetupDatabase(IWebHost host) LiteDB.LiteException: File is not a valid LiteDB database format or contains a invalid password.
   at LiteDB.Engine.HeaderPage.LoadPage()
   at LiteDB.Engine.HeaderPage..ctor(PageBuffer buffer)
   at LiteDB.Engine.LiteEngine..ctor(EngineSettings settings)
   at LiteDB.SharedEngine.OpenDatabase()
   at LiteDB.SharedEngine.EnsureIndex(String collection, String name, BsonExpression expression, Boolean unique)
   at LiteDB.LiteCollection`1.EnsureIndex(String name, BsonExpression expression, Boolean unique)
   at LiteDB.LiteCollection`1.EnsureIndex(BsonExpression expression, Boolean unique)
   at LiteDB.LiteCollection`1.EnsureIndex[K](Expression`1 keySelector, Boolean unique)
   at EmbyStat.Repositories.DatabaseInitializer.CreateIndexes()
   at EmbyStat.Web.Program.SetupDatabase(IWebHost host)
2020-04-10 11:01:11.0092 [FATAL] SYSTEM Server terminated unexpectedly LiteDB.LiteException: File is not a valid LiteDB database format or contains a invalid password.
   at LiteDB.Engine.HeaderPage.LoadPage()
   at LiteDB.Engine.HeaderPage..ctor(PageBuffer buffer)
   at LiteDB.Engine.LiteEngine..ctor(EngineSettings settings)
   at LiteDB.SharedEngine.OpenDatabase()
   at LiteDB.SharedEngine.EnsureIndex(String collection, String name, BsonExpression expression, Boolean unique)
   at LiteDB.LiteCollection`1.EnsureIndex(String name, BsonExpression expression, Boolean unique)
   at LiteDB.LiteCollection`1.EnsureIndex(BsonExpression expression, Boolean unique)
   at LiteDB.LiteCollection`1.EnsureIndex[K](Expression`1 keySelector, Boolean unique)
   at EmbyStat.Repositories.DatabaseInitializer.CreateIndexes()
   at EmbyStat.Web.Program.SetupDatabase(IWebHost host)
   at EmbyStat.Web.Program.Main(String[] args)
2020-04-10 11:01:11.0092 [INFO] SYSTEM  Server shutdown

**Comment by mregni** [comment]
Hey, thanks for the logs!

The update to beta.17 (and later) is breaking meaning you have to install a new instance of the linuxserver image. The issue is that I had to move some settings files around, the linuxserver guys are fixing the issue. 

Breaking change to beta.17 is that I moved to LiteDB V5 and that needs a completely new database file. So please remove all embystat files and install a new instance of the linuxserver image.

Let me know if that fixes your issue.

**Comment by deeprain279** [comment]
Hello,
thank you for the feedback. I create a complete new container and all works perfect now like it was in Beta 15.

The question can be closed. THX

**Comment by mregni** [comment]
Thanks for your reply! happy to help :)
