### ISSUE TITLE
Duplicate exception on resync

### ISSUE THREAD

**Issue by mregni** [mregni/EmbyStat#1156]
Looks like there are some leftovers in the database because a resync will crash sometimes. 

```2020-04-08 17:05:04.6263 [ERROR] Error while running job LiteDB.LiteException: Cannot insert duplicate key in unique index '_id'. The duplicate value is '"123394"'.
   at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, Byte level, IndexNode last)
   at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, IndexNode last)
   at LiteDB.Engine.LiteEngine.InsertDocument(Snapshot snapshot, BsonDocument doc, BsonAutoId autoId, IndexService indexer, DataService data)
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass7_0.<Insert>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.SharedEngine.Insert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at EmbyStat.Repositories.ShowRepository.<>c__DisplayClass6_0.<InsertShow>b__0()
   at EmbyStat.Repositories.BaseRepository.ExecuteQuery(Action query)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.PerformShowSyncAsync(IReadOnlyList`1 showsThatNeedAnUpdate, Library library, DateTime updateStartTime)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessShowsAsync(IEnumerable`1 libraries, CancellationToken cancellationToken)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()```

**Comment by deeprain279** [comment]
Same issue here. The first sync or the initial sync was perfect. The scheduled sync or other sync are failed:

2020-04-11 13:06:14.5133 [INFO] THETVDB-CLIENT	Call to THETVDB: https://api.thetvdb.com/series/72449/episodes?page=2 
2020-04-11 13:06:14.5858 [INFO] THETVDB-CLIENT	Call to THETVDB: https://api.thetvdb.com/series/72449/episodes?page=3 
2020-04-11 13:06:14.6440 [INFO] MEDIASYNC-JOB	Found 0 missing episodes for show Stargate 
2020-04-11 13:06:16.2812 [INFO] Connecting to wss://xxx.xxx.xxx.xxx:xxxx/embywebsocket?api_key=xxxxxxxxxxxxxx&deviceId=3ddc4eb4-e3de-438d-ac5e-f7eee12f2405 
2020-04-11 13:06:18.1201 [ERROR] Error while running job LiteDB.LiteException: Cannot insert duplicate key in unique index '_id'. The duplicate value is '"88101"'.
   at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, Byte level, IndexNode last)
   at LiteDB.Engine.LiteEngine.InsertDocument(Snapshot snapshot, BsonDocument doc, BsonAutoId autoId, IndexService indexer, DataService data)
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass7_0.<Insert>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.SharedEngine.Insert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at EmbyStat.Repositories.ShowRepository.<>c__DisplayClass6_0.<InsertShow>b__0()
   at EmbyStat.Repositories.BaseRepository.ExecuteQuery(Action query)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.PerformShowSyncAsync(IReadOnlyList`1 showsThatNeedAnUpdate, Library library, DateTime updateStartTime)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessShowsAsync(IEnumerable`1 libraries, CancellationToken cancellationToken)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()
2020-04-11 13:06:18.5627 [ERROR] MEDIASYNC-JOB	Job failed, check logs for more info. 
2020-04-11 13:06:18.7609 [WARN] Failed to process the job 'ac75e258-8a6e-4db4-87b1-81f0c7f1312a': an exception occurred. Retry attempt 1 of 2 will be performed in 00:00:32. LiteDB.LiteException: Cannot insert duplicate key in unique index '_id'. The duplicate value is '"88101"'.
   at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, Byte level, IndexNode last)
   at LiteDB.Engine.LiteEngine.InsertDocument(Snapshot snapshot, BsonDocument doc, BsonAutoId autoId, IndexService indexer, DataService data)
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass7_0.<Insert>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.SharedEngine.Insert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at EmbyStat.Repositories.ShowRepository.<>c__DisplayClass6_0.<InsertShow>b__0()
   at EmbyStat.Repositories.BaseRepository.ExecuteQuery(Action query)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.PerformShowSyncAsync(IReadOnlyList`1 showsThatNeedAnUpdate, Library library, DateTime updateStartTime)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessShowsAsync(IEnumerable`1 libraries, CancellationToken cancellationToken)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()
   at EmbyStat.Jobs.BaseJob.Execute()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2020-04-11 13:06:21.2805 [INFO] Connecting to wss://xxx.xxx.xxx.xxx:xxxx/embywebsocket?api_key=xxxxxxxxxxxxxx&deviceId=3ddc4eb4-e3de-438d-ac5e-f7eee12f2405 
2020-04-11 13:06:26.2808 [INFO] Connecting to wss://xxx.xxx.xxx.xxx:xxxx/embywebsocket?api_key=xxxxxxxxxxxxxx&deviceId=3ddc4eb4-e3de-438d-ac5e-f7eee12f2405

**Comment by mregni** [comment]
This is normally fixed in a previous version, closing the issue for now. Feel free to reopen or create a new one if the issue is not fixed.
