### ISSUE TITLE
Jellyfin scan error

### ISSUE THREAD

**Issue by wizel10** [mregni/EmbyStat#1184]
# Bug report

**Describe the bug**
Through an error when media sync starts.

**To Reproduce**
Connected to Jellyfin OK. Working on a container (docker) with network set as host.
Check connection is OK
Media sync fails.

**Expected behavior**
Sync to take place

**Screenshots**

**System (please complete the following information):**

- OS: [e.g. Windows, Ubuntu]: Debian running OMV 5 with Jellyfin and Embystat in Docker
- Browser [e.g. chrome, safari]: Brave

**Additional context**
Error log:
2020-04-21 22:13:42.4131 [INFO] DATABASE CLEANUP-JOB	Starting job 
2020-04-21 22:13:42.4464 [INFO] DATABASE CLEANUP-JOB	Removed old statistic results. 
2020-04-21 22:13:42.4653 [INFO] DATABASE CLEANUP-JOB	Job finished after 1 minute. 
2020-04-21 22:13:57.6827 [INFO] CHECKUDPATE-JOB	Starting job 
2020-04-21 22:13:57.7024 [INFO] CHECKUDPATE-JOB	Contacting Github now to see if new version is available. 
2020-04-21 22:13:58.5303 [INFO] CHECKUDPATE-JOB	No new version available 
2020-04-21 22:13:58.5513 [INFO] CHECKUDPATE-JOB	Job finished after 1 minute. 
2020-04-21 22:14:13.5815 [INFO] SMALLEMBYSYNC-JOB	Starting job 
2020-04-21 22:14:13.6263 [INFO] SMALLEMBYSYNC-JOB	Server info downloaded 
2020-04-21 22:14:13.6608 [INFO] SMALLEMBYSYNC-JOB	Server plugins downloaded 
2020-04-21 22:14:13.7058 [INFO] SMALLEMBYSYNC-JOB	Server users downloaded 
2020-04-21 22:14:13.7557 [INFO] SMALLEMBYSYNC-JOB	Server devices downloaded 
2020-04-21 22:14:13.7716 [INFO] SMALLEMBYSYNC-JOB	Job finished after 1 minute. 
2020-04-21 22:14:28.8669 [INFO] MEDIASYNC-JOB	Starting job 
2020-04-21 22:14:28.8854 [INFO] MEDIASYNC-JOB	First delete all existing media and root media libraries from database so we have a clean start. 
2020-04-21 22:14:28.8854 [INFO] MEDIASYNC-JOB	Asking MediaServer for all root folders 
2020-04-21 22:14:28.9044 [INFO] MEDIASYNC-JOB	Found 3 root items, getting ready for processing 
2020-04-21 22:14:28.9044 [INFO] MEDIASYNC-JOB	Lets start processing movies 
2020-04-21 22:14:28.9223 [WARN] MEDIASYNC-JOB	0 movies found in parent with id f137a2dd21bbc1b99aa5c0f6bf02a805. Propably means something is wrong with the HTTP call. 
2020-04-21 22:14:28.9223 [INFO] MEDIASYNC-JOB	Lets start processing show 
2020-04-21 22:14:28.9223 [INFO] MEDIASYNC-JOB	Logging in on the Tvdb API. 
2020-04-21 22:14:30.3537 [ERROR] Error while running job System.NullReferenceException: Object reference not set to an instance of an object.
   at EmbyStat.Clients.Base.Http.BaseHttpClient.GetShows(String parentId)
   at EmbyStat.Clients.Jellyfin.Http.JellyfinHttpClient.EmbyStat.Clients.Base.Http.IHttpClient.GetShows(String libraryId)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.PerformShowSyncAsync(IReadOnlyList`1 showsThatNeedAnUpdate, Library library, DateTime updateStartTime)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessShowsAsync(IEnumerable`1 libraries, CancellationToken cancellationToken)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()
2020-04-21 22:14:30.3979 [WARN] MEDIASYNC-JOB	Job failed, check logs for more info. 
2020-04-21 22:14:30.7666 [WARN] Failed to process the job '02abb60a-9e82-4224-9a8f-f4b076f1607f': an exception occurred. Retry attempt 1 of 2 will be performed in 00:00:18. System.NullReferenceException: Object reference not set to an instance of an object.
   at EmbyStat.Clients.Base.Http.BaseHttpClient.GetShows(String parentId)
   at EmbyStat.Clients.Jellyfin.Http.JellyfinHttpClient.EmbyStat.Clients.Base.Http.IHttpClient.GetShows(String libraryId)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.PerformShowSyncAsync(IReadOnlyList`1 showsThatNeedAnUpdate, Library library, DateTime updateStartTime)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessShowsAsync(IEnumerable`1 libraries, CancellationToken cancellationToken)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()
   at EmbyStat.Jobs.BaseJob.Execute()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by wizel10** [comment]
Did a second test with Emby, rather than JellyFin, and works very fine. reading through other issues I saw the connection with Jellyfin is not yet finish or stable.
I'll close this issue as the team is well aware.
Thanks for the good job.
