### ISSUE TITLE
Emby plugin not working - ( failed ) 

### ISSUE THREAD

**Issue by sesipod** [mregni/EmbyStat#1221]
# Bug report

**Describe the bug**
Error when running the Statistics update from scheduled tasks ( failed )

**To Reproduce**

1. Uninstalled the plugin / restart server / reinstall plugin
2. Run the task manually - same error

**Expected behavior**
For the scan to complete and user stats to be updated.

**Screenshots**
![image](https://user-images.githubusercontent.com/1533744/82282535-abb31200-9959-11ea-864e-68a2f938fd4b.png)

**System (please complete the following information):**

- OS: Linux - Debian 10.2
- Browser Chrome / Firefox - does not matter

**Additional context**

**Comment by sesipod** [comment]
[Emby-Server-Log](https://share.sshosting.org/de353e99b97c)

**Comment by sesipod** [comment]
`Value cannot be null. (Parameter 'source')
at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at Statistics.ScheduledTasks.CalculateStatsTask.UpdateTvdbConnection(ShowProgressCalculator calculator, String time, IEnumerable`1 seriesIdsInLibrary, CancellationToken cancellationToken)
at Statistics.ScheduledTasks.CalculateStatsTask.CalculateTotalEpisodes(CancellationToken cancellationToken)
at Statistics.ScheduledTasks.CalculateStatsTask.MediaBrowser.Model.Tasks.IScheduledTask.Execute(CancellationToken cancellationToken, IProgress`1 progress)
at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)`

**Comment by oonqt** [comment]
The plugin got an update that fixed this
