### ISSUE TITLE
Emby Beta throws null ref in stream sync

### ISSUE THREAD

**Issue by mregni** [mregni/EmbyStat#1323]
This is interesting as I have a Test stable and beta Emby servers and ,22 will run on fine but my primary Emby Beta server throws this error.

2020-08-12 15:07:58.2574 [WARN] MEDIA-SYNC	Movie error: Object reference not set to an instance of an object. 
2020-08-12 15:07:58.2574 [ERROR] Error while running job System.NullReferenceException: Object reference not set to an instance of an object.
   at EmbyStat.Common.Extensions.BaseItemDtoExtension.<>c__2`1.<MapPeople>b__2_0(BaseItemPerson y)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToArray()
   at EmbyStat.Common.Extensions.BaseItemDtoExtension.MapPeople[T](BaseItemDto dto, T extra)
   at EmbyStat.Clients.Base.Converters.MovieConverter.ConvertToMovie(BaseItemDto dto, String collectionId)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.PerformMovieSyncAsync(String parentId, String collectionId, Int32 startIndex, Int32 limit)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.PerformMovieSyncAsync(String parentId, String collectionId, Int32 startIndex, Int32 limit)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessMoviesAsync(IReadOnlyList`1 libraries, CancellationToken cancellationToken)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()
2020-08-12 15:07:58.2797 [WARN] MEDIA-SYNC	Job failed, check logs for more info. 
2020-08-12 15:07:58.3616 [ERROR] Failed to process the job '4dc1e15c-bb29-4097-8d81-c2e02034a3ff': an exception occurred. System.NullReferenceException: Object reference not set to an instance of an object.
   at EmbyStat.Common.Extensions.BaseItemDtoExtension.<>c__2`1.<MapPeople>b__2_0(BaseItemPerson y)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToArray()
   at EmbyStat.Common.Extensions.BaseItemDtoExtension.MapPeople[T](BaseItemDto dto, T extra)
   at EmbyStat.Clients.Base.Converters.MovieConverter.ConvertToMovie(BaseItemDto dto, String collectionId)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.PerformMovieSyncAsync(String parentId, String collectionId, Int32 startIndex, Int32 limit)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.PerformMovieSyncAsync(String parentId, String collectionId, Int32 startIndex, Int32 limit)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessMoviesAsync(IReadOnlyList`1 libraries, CancellationToken cancellationToken)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()
   at EmbyStat.Jobs.BaseJob.Execute()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

_Originally posted by @Happy2Play in https://github.com/mregni/EmbyStat/issues/1266#issuecomment-673191311_

**Comment by mregni** [comment]
@Happy2Play, I create a seperate issue for your bug because it's another problem. Can you also start the nightly build? (only on docker for the moment) 
`docker run -v <local-data-path>:C:\app\data -p <port>:6555 -e EMBYSTAT_LOGLEVEL=1 uping/embystat:nightly`

I added a lot of debug logs in that build that would give me more information about what property is not returned by Emby Beta anymore (or may be nullable).

**Comment by Happy2Play** [comment]
Have never used Docker before, but the previous log seemed to point to a issue in the Movies - Kids library library so I did a Refresh and told Emby to search for missing metadata and now the Sync finishes.

3:14:40 PM 08/13/2020 - MEDIA-SYNC - Job finished after 4 minutes.

Different issue but there is no TV in the UI or scanned even though configured libraries in the Wizard.

Okay just saw your note in Emby forum and in previous version release notes.

Disabled shows for now (will be included in the next release)

So All is good again.

**Comment by mregni** [comment]
Oke, will close this issue for now. Feel free to open it when the error returns!
