### ISSUE TITLE
MEDIA-SYNC - Job failed, check logs for more info

### ISSUE THREAD

**Issue by ShakeSp33r** [mregni/EmbyStat#1349]
# Bug report

**Describe the bug**
System start syncing the library from Jellyfin and stop after a couple of seconds with nothing synced.

**To Reproduce**
1. Click on Movies
2. "No movies found" screen appears
3. Click on "Start Media Sync"

**System (please complete the following information):**
- OS: Docker (linuxserver/embystat)
- Browser Safari, Chrome, Opera, Firefox
- Version 0.2.0-beta.23
- Media server type Jellyfin 10.6.2

**Additional context**
2020-08-31 04:33:40.7708 [INFO] SYSTEM	-------------------------------------------------------------------- 
2020-08-31 04:33:40.7961 [INFO] SYSTEM	Booting up server with following options: 
2020-08-31 04:33:40.7961 [INFO] SYSTEM		Log level:		Information 
2020-08-31 04:33:40.7961 [INFO] SYSTEM		Port:			6555 
2020-08-31 04:33:40.7961 [INFO] SYSTEM		URL's:			http://* 
2020-08-31 04:33:40.7961 [INFO] SYSTEM		ConfigDir:		/config 
2020-08-31 04:33:40.7961 [INFO] SYSTEM		DataDir:		/config 
2020-08-31 04:33:40.7961 [INFO] SYSTEM		LogDir:			/config/logs 
2020-08-31 04:33:40.7961 [INFO] SYSTEM		Updates enabled:	False 
2020-08-31 04:33:40.7961 [INFO] SYSTEM		Running as service:	False 
2020-08-31 04:33:40.7961 [INFO] SYSTEM	-------------------------------------------------------------------- 
2020-08-31 04:33:41.4409 [INFO] Starting Hangfire Server using job storage: 'Hangfire.MemoryStorage.MemoryStorage' 
2020-08-31 04:33:41.4434 [INFO] Using the following options for Hangfire Server:
    Worker count: 1
    Listening queues: 'main'
    Shutdown timeout: 1.00:00:00
    Schedule polling interval: 00:00:05 
2020-08-31 04:33:41.6079 [INFO] Server main server:251:3c2c927a successfully announced in 137.114 ms 
2020-08-31 04:33:41.6119 [INFO] Server main server:251:3c2c927a is starting the registered dispatchers: ServerWatchdog, ServerJobCancellationWatcher, ExpirationManager, CountersAggregator, Worker, DelayedJobScheduler, RecurringJobScheduler... 
2020-08-31 04:33:41.6224 [INFO] Server main server:251:3c2c927a all the dispatchers started 
2020-08-31 04:33:56.6612 [INFO] MEDIA-SYNC	Starting job 
2020-08-31 04:33:57.0149 [INFO] MEDIA-SYNC	First delete all existing media and root media libraries from database so we have a clean start. 
2020-08-31 04:33:57.0178 [INFO] MEDIA-SYNC	Asking MediaServer for all root folders 
2020-08-31 04:33:57.1464 [INFO] MEDIA-SYNC	Found 6 root items, getting ready for processing 
2020-08-31 04:33:57.1544 [INFO] MEDIA-SYNC	Lets start processing movies 
2020-08-31 04:33:57.7215 [INFO] MEDIA-SYNC	Found 1358 movies in Movies library 
2020-08-31 04:33:59.1359 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-08-31 04:33:59.1516 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-08-31 04:33:59.1516 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-08-31 04:33:59.1516 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-08-31 04:33:59.1516 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-08-31 04:33:59.1516 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-08-31 04:33:59.1516 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-08-31 04:33:59.1516 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-08-31 04:33:59.1516 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-08-31 04:33:59.1516 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-08-31 04:33:59.1516 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-08-31 04:33:59.1516 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-08-31 04:33:59.1516 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-08-31 04:33:59.1516 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-08-31 04:33:59.1516 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-08-31 04:33:59.1516 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-08-31 04:33:59.1516 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-08-31 04:33:59.1516 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-08-31 04:33:59.1516 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-08-31 04:33:59.1558 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-08-31 04:33:59.1558 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-08-31 04:33:59.1558 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-08-31 04:33:59.1558 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-08-31 04:33:59.1558 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-08-31 04:33:59.1609 [ERROR] Error while running job System.ArgumentNullException: Value cannot be null. (Parameter 'entity')
   at LiteDB.BsonMapper.ToDocument(Type type, Object entity)
   at LiteDB.BsonMapper.ToDocument[T](T entity)
   at LiteDB.LiteCollection`1.GetBsonDocs(IEnumerable`1 documents)+MoveNext()
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass30_0.<Upsert>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.Engine.LiteEngine.Upsert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at LiteDB.SharedEngine.Upsert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at LiteDB.LiteCollection`1.Upsert(IEnumerable`1 entities)
   at EmbyStat.Repositories.MovieRepository.<>c__DisplayClass1_0.<UpsertRange>b__0()
   at EmbyStat.Repositories.BaseRepository.ExecuteQuery(Action query)
   at EmbyStat.Repositories.MovieRepository.UpsertRange(IEnumerable`1 movies)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessMoviesAsync(IReadOnlyList`1 libraries, CancellationToken cancellationToken)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()
2020-08-31 04:33:59.1942 [WARN] MEDIA-SYNC	Job failed, check logs for more info. 
2020-08-31 04:33:59.3649 [WARN] Failed to process the job '9882794c-afcd-439b-be61-041b8e235289': an exception occurred. Retry attempt 1 of 2 will be performed in 00:00:22. System.ArgumentNullException: Value cannot be null. (Parameter 'entity')
   at LiteDB.BsonMapper.ToDocument(Type type, Object entity)
   at LiteDB.BsonMapper.ToDocument[T](T entity)
   at LiteDB.LiteCollection`1.GetBsonDocs(IEnumerable`1 documents)+MoveNext()
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass30_0.<Upsert>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.Engine.LiteEngine.Upsert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at LiteDB.SharedEngine.Upsert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at LiteDB.LiteCollection`1.Upsert(IEnumerable`1 entities)
   at EmbyStat.Repositories.MovieRepository.<>c__DisplayClass1_0.<UpsertRange>b__0()
   at EmbyStat.Repositories.BaseRepository.ExecuteQuery(Action query)
   at EmbyStat.Repositories.MovieRepository.UpsertRange(IEnumerable`1 movies)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessMoviesAsync(IReadOnlyList`1 libraries, CancellationToken cancellationToken)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()
   at EmbyStat.Jobs.BaseJob.Execute()
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

**Comment by mregni** [comment]
Thanks for logging this bug!
Looks like I need to add some more debug information to see what property is null for some odd reason. I will let you know asap when I can create a nightly build for this so you can rerun your tests.

**Comment by ShakeSp33r** [comment]
I have excluded the Movies, and the Shows are now processing without an issue. I will after the scan finished do a Library update in Jellyfin, to make sure there are no deleted Movies & then try and process the Movies again... Will let you know.

**Comment by ShakeSp33r** [comment]
Enabled Movies to scan, no luck. 

Upgraded to Version 0.2.0-beta.24

Try another scan with Movies enabled. Still same thing:

2020-09-18 10:19:35.0518 [INFO] MEDIA-SYNC	Found 865 movies in Movies library 
2020-09-18 10:19:38.3532 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-09-18 10:19:38.3589 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-09-18 10:19:38.3589 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-09-18 10:19:38.3589 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-09-18 10:19:38.3589 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-09-18 10:19:38.3589 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-09-18 10:19:38.3589 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-09-18 10:19:38.3589 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-09-18 10:19:38.3589 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-09-18 10:19:38.3589 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-09-18 10:19:38.3589 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-09-18 10:19:38.3610 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-09-18 10:19:38.3610 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-09-18 10:19:38.3610 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-09-18 10:19:38.3610 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-09-18 10:19:38.3610 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-09-18 10:19:38.4546 [ERROR] Error while running job System.NullReferenceException: Object reference not set to an instance of an object.
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.<>c.<ProcessMoviesAsync>b__17_2(Movie x)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at LiteDB.LiteCollection`1.GetBsonDocs(IEnumerable`1 documents)+MoveNext()
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass30_0.<Upsert>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.SharedEngine.Upsert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at EmbyStat.Repositories.MovieRepository.<>c__DisplayClass1_0.<UpsertRange>b__0()
   at EmbyStat.Repositories.BaseRepository.ExecuteQuery(Action query)
   at EmbyStat.Repositories.MovieRepository.UpsertRange(IEnumerable`1 movies)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessMoviesAsync(IReadOnlyList`1 libraries, CancellationToken cancellationToken)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()
2020-09-18 10:19:38.6059 [WARN] MEDIA-SYNC	Job failed, check logs for more info. 
2020-09-18 10:19:38.8233 [WARN] Failed to process the job '5ae3e2f1-9a1a-436b-ba37-3ee757d7b46a': an exception occurred. Retry attempt 1 of 2 will be performed in 00:00:26. System.NullReferenceException: Object reference not set to an instance of an object.
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.<>c.<ProcessMoviesAsync>b__17_2(Movie x)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at LiteDB.LiteCollection`1.GetBsonDocs(IEnumerable`1 documents)+MoveNext()
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass30_0.<Upsert>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.SharedEngine.Upsert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at EmbyStat.Repositories.MovieRepository.<>c__DisplayClass1_0.<UpsertRange>b__0()
   at EmbyStat.Repositories.BaseRepository.ExecuteQuery(Action query)
   at EmbyStat.Repositories.MovieRepository.UpsertRange(IEnumerable`1 movies)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessMoviesAsync(IReadOnlyList`1 libraries, CancellationToken cancellationToken)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()
   at EmbyStat.Jobs.BaseJob.Execute()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by mregni** [comment]
This seems to be a different error. I'll see why you get a nullref exception and try to fix it.

**Comment by scicomrunner** [comment]
I ran into this same/similar problem no media would sync. exception errors base client can not be null etc. I noticed in the log that the movie count was not complete, it was the count of Movies/Collections not the full movie count. I went into my Jellyfin server and turned off Group Movies into Collections in the library settings, and bingo EmbyStat started to sync. Not a long term solution as I prefer to have my movies displayed in their collections when browsing  (Jellyfin 10.6.4 EmbyStat .2.24)

**Comment by the-lazy-fox** [comment]
Please note that you need to select server type as Jellyfin and not Emby if you connect to a Jellyfin instance, it seems obvious but the option selector is not easy to see in the wizard.
Don't know if it's the root cause but might be.

**Comment by ShakeSp33r** [comment]
I followed @scicomrunner thought and disabled the Group Movies into Collections, and now my null error is a thing of the past. It scanned TVShows & Movies, not just TVShows...
