### ISSUE TITLE
 MEDIA-SYNC - Job failed 

### ISSUE THREAD

**Issue by Ishannaik** [mregni/EmbyStat#1440]
# Bug report

**Describe the bug**

```
9:51:56 AM 12/19/2020 - MEDIA-SYNC - Starting job
9:51:56 AM 12/19/2020 - MEDIA-SYNC - First delete all existing media and root media libraries from database so we have a clean start.
9:51:56 AM 12/19/2020 - MEDIA-SYNC - Asking MediaServer for all root folders
9:51:56 AM 12/19/2020 - MEDIA-SYNC - Found 5 root items, getting ready for processing
9:51:56 AM 12/19/2020 - MEDIA-SYNC - Lets start processing movies
9:51:57 AM 12/19/2020 - MEDIA-SYNC - 0 movies found in parent with id 0c41907140d802bb58430fed7e2cd79e. Probably means something is wrong with the HTTP call.
9:51:57 AM 12/19/2020 - MEDIA-SYNC - Found 63 movies in Movies library
9:51:57 AM 12/19/2020 - MEDIA-SYNC - Job failed, check logs for more info.
```
LOGS

```
2020-12-25 06:23:46.1496 [INFO] MEDIA-SYNC	Starting job 
2020-12-25 06:23:46.1776 [INFO] MEDIA-SYNC	First delete all existing media and root media libraries from database so we have a clean start. 
2020-12-25 06:23:46.1776 [INFO] MEDIA-SYNC	Asking MediaServer for all root folders 
2020-12-25 06:23:46.1967 [INFO] MEDIA-SYNC	Found 6 root items, getting ready for processing 
2020-12-25 06:23:46.1967 [INFO] MEDIA-SYNC	Lets start processing movies 
2020-12-25 06:23:46.2756 [INFO] MEDIA-SYNC	Found 169 movies in Movies library 
2020-12-25 06:23:46.9746 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-12-25 06:23:46.9746 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-12-25 06:23:46.9746 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-12-25 06:23:46.9746 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-12-25 06:23:46.9768 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-12-25 06:23:46.9768 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-12-25 06:23:46.9768 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-12-25 06:23:46.9768 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-12-25 06:23:46.9768 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-12-25 06:23:46.9768 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-12-25 06:23:46.9768 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-12-25 06:23:46.9768 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-12-25 06:23:46.9768 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-12-25 06:23:46.9768 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-12-25 06:23:46.9768 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-12-25 06:23:46.9768 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-12-25 06:23:46.9768 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-12-25 06:23:46.9768 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-12-25 06:23:46.9768 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-12-25 06:23:46.9807 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-12-25 06:23:46.9807 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-12-25 06:23:46.9807 [WARN] BASE-HTTP-CLIENT	Value cannot be null. (Parameter 'source') 
2020-12-25 06:23:46.9903 [ERROR] Error while running job System.NullReferenceException: Object reference not set to an instance of an object.
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.<>c.<ProcessMoviesAsync>b__17_2(Movie x)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at LiteDB.LiteCollection`1.GetBsonDocs(IEnumerable`1 documents)+MoveNext()
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass30_0.<Upsert>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.Engine.LiteEngine.Upsert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at LiteDB.SharedEngine.Upsert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at LiteDB.LiteCollection`1.Upsert(IEnumerable`1 entities)
   at EmbyStat.Repositories.MovieRepository.<>c__DisplayClass1_0.<UpsertRange>b__0()
   at EmbyStat.Repositories.BaseRepository.ExecuteQuery(Action query)
   at EmbyStat.Repositories.MovieRepository.UpsertRange(IEnumerable`1 movies)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessMoviesAsync(IReadOnlyList`1 libraries, CancellationToken cancellationToken)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()
```
**To Reproduce**

Click on run mediasync

**Expected behavior**

Run mediasync

**Screenshots**

**System (please complete the following information):**

- OS: [e.g. Windows, Ubuntu] -Ubuntu
- Browser [e.g. chrome, safari] - chrome 
- Version [e.g. 22] - beta from docker
- Media server type [e.g. Emby/Jellyfin] - jellyfin

**Comment by mregni** [comment]
Hi @Ishannaik, sorry I didn't reply to your issue sooner! The project has been in sleep modus for some time but I'm starting to work on it again.

I'm adding a specific NULL check so I don't insert wrong data, but we have to see if this is a good fix for your issue. It will be included in beta.27 soon.

**Comment by mregni** [comment]
Can you check if this is working now with beta.27? I added the NULL check that probably will fix this issue
