### ISSUE TITLE
Blank screen after inputting server details on setup wizard

### ISSUE THREAD

**Issue by Nestar47** [mregni/EmbyStat#1588]
After filling in the server settings in the web UI, there is a quick flash of a screen showing something about loading users, then the screen goes white. 

Extract and copy debian x64 release beta 26 to /var/lib/EmbyStat
Allow execute on ./EmbyStat
Run
Connect to web UI on port 6555
Fill in user/pass
Select new server
Fill in relevant details and hit next

**Expected behavior**
Expect to see page 5 of the setup wizard

**System (please complete the following information):**

- OS: Debian 9 and 10 (tried on a separate vm as well to rule out issues from a previous install)
- Browser: Chrome and Firefox
- Version 0.2 Beta 26
- Media server type Emby 4.6.0.50

**Comment by Nestar47** [comment]
Just tested Beta 25 as well, same thing there.

**Comment by Nestar47** [comment]
Log entry from a corresponding attempt.

```
2021-08-02 17:15:14.1991 [INFO] SYSTEM  --------------------------------------------------------------------
2021-08-02 17:15:14.2357 [INFO] SYSTEM  Booting up server with following options:
2021-08-02 17:15:14.2357 [INFO] SYSTEM          Log level:              Information
2021-08-02 17:15:14.2357 [INFO] SYSTEM          Port:                   6555
2021-08-02 17:15:14.2357 [INFO] SYSTEM          URL's:                  http://*
2021-08-02 17:15:14.2357 [INFO] SYSTEM          ConfigDir:              /var/lib/EmbyStat
2021-08-02 17:15:14.2357 [INFO] SYSTEM          DataDir:                /var/lib/EmbyStat
2021-08-02 17:15:14.2357 [INFO] SYSTEM          LogDir:                 /var/lib/EmbyStat/logs
2021-08-02 17:15:14.2357 [INFO] SYSTEM          Updates enabled:        True
2021-08-02 17:15:14.2357 [INFO] SYSTEM          Running as service:     False
2021-08-02 17:15:14.2357 [INFO] SYSTEM  --------------------------------------------------------------------
2021-08-02 17:15:15.0340 [INFO] Starting Hangfire Server using job storage: 'Hangfire.MemoryStorage.MemoryStorage'
2021-08-02 17:15:15.0356 [INFO] Using the following options for Hangfire Server:
    Worker count: 1
    Listening queues: 'main'
    Shutdown timeout: 1.00:00:00
    Schedule polling interval: 00:00:05
2021-08-02 17:15:15.1866 [INFO] Server main server:6284:dfa00a4a successfully announced in 136.2192 ms
2021-08-02 17:15:15.1905 [INFO] Server main server:6284:dfa00a4a is starting the registered dispatchers: ServerWatchdog, ServerJobCancellationWatcher, ExpirationManager, CountersAggregator, Worker, DelayedJobScheduler, RecurringJobScheduler...
2021-08-02 17:15:15.1930 [INFO] Server main server:6284:dfa00a4a all the dispatchers started
2021-08-02 17:15:39.4655 [ERROR] An unhandled error occurred. System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, String parameterName)
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at Newtonsoft.Json.Linq.Extensions.Value[U](IEnumerable`1 value)
   at EmbyStat.Common.Converters.UserConverter.<>c.<ConvertToUserList>b__0_0(JToken user)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at EmbyStat.Common.Converters.UserConverter.ConvertToUserList(JArray model)
   at EmbyStat.Services.MediaServerService.GetAndProcessUsers()
   at EmbyStat.Services.MediaServerService.GetAllAdministrators()
   at EmbyStat.Controllers.MediaServer.MediaServerController.GetAdministrators()
   at lambda_method801(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2021-08-02 17:20:15.2371 [WARN] PING    Job not running because wizard is not finished
2021-08-02 17:25:15.3170 [WARN] PING    Job not running because wizard is not finished
2021-08-02 17:30:00.3898 [WARN] PING    Job not running because wizard is not finished
2021-08-02 17:35:00.4920 [WARN] PING    Job not running because wizard is not finished
2021-08-02 17:40:00.5843 [WARN] PING    Job not running because wizard is not finished
2021-08-02 17:45:00.6695 [WARN] PING    Job not running because wizard is not finished
2021-08-02 17:50:00.7844 [WARN] PING    Job not running because wizard is not finished
2021-08-02 17:55:00.8669 [WARN] PING    Job not running because wizard is not finished
2021-08-02 18:00:00.9869 [WARN] PING    Job not running because wizard is not finished
2021-08-02 18:03:55.2591 [INFO] Server main server:6284:dfa00a4a caught stopping signal...
2021-08-02 18:03:55.2591 [INFO] Server main server:6284:dfa00a4a caught stopped signal...
2021-08-02 18:03:55.2591 [INFO] Server main server:6284:dfa00a4a All dispatchers stopped
2021-08-02 18:03:55.2650 [INFO] Server main server:6284:dfa00a4a successfully reported itself as stopped in 0.3166 ms
2021-08-02 18:03:55.2650 [INFO] Server main server:6284:dfa00a4a has been stopped in total 5.4958 ms
2021-08-02 18:03:55.3100 [INFO] SYSTEM  Server shutdown
```

**Comment by shakey555** [comment]
Same behaviour here for me in beta 25 and 26 on win10.
Upgrading from within embystat does not work either, so no way past the wizard for me.

**Comment by mregni** [comment]
Same bug is also logged on the Emby forum. I'm going to add some default values in the user converter so it won't crash again.

**Comment by Nestar47** [comment]
Setup now completes successfully for me on beta 27 Debian x64

**Comment by hayrun-st** [comment]
I'm seeing the same thing on the Linux Server docker image using the latest version.

2022-05-05 19:57:51.1355 [ERROR] An unhandled error occurred. System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, String parameterName)
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at Newtonsoft.Json.Linq.Extensions.Value[U](IEnumerable`1 value)
   at EmbyStat.Common.Converters.UserConverter.<>c.<ConvertToUserList>b__0_0(JToken user)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at EmbyStat.Common.Converters.UserConverter.ConvertToUserList(JArray model)
   at EmbyStat.Services.MediaServerService.GetAndProcessUsers()
   at EmbyStat.Services.MediaServerService.GetAllAdministrators()
   at EmbyStat.Controllers.MediaServer.MediaServerController.GetAdministrators()
   at lambda_method801(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---

**Comment by plittlefield** [comment]
Same here on Docker latest from linuxserver.io and just after inputting API key.

Also, it never finds the local server, so I have to input it manually.

**Comment by plittlefield** [comment]
https://pastebin.com/w1S7MKfe

**Comment by tomlawesome** [comment]
This is an ongoing issue. Also using LSIO container though, so perhaps there is a problem there?
