### ISSUE TITLE
Crash when viewing trailer before a movie

### ISSUE THREAD

**Issue by hbooo** [mregni/EmbyStat#538]
# Bug report
EmbyStat crashs after playing a movie with cinema mode activated

**Describe the bug**
EmbyStat stop working

**To Reproduce**
Have cinema mode activated with local trailers
Play a movie
Trailer is played before movie
EmbyStat stop working

**Expected behavior**
EmbyStat shouldn't crash

**Screenshots**
None

**System (please complete the following information):**

- OS: Unraid
- Version : nightly-linux

**Additional context**
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:5432
Application started. Press Ctrl+C to shut down.

Unhandled Exception: System.ArgumentException: Could not convert 'Trailer' to PlayType. ---> Newtonsoft.Json.JsonSerializationException: Error converting value "Trailer" to type 'EmbyStat.Common.Enums.PlayType'. Path '[0].NowPlayingItem.Type'. ---> System.ArgumentException: Requested value 'Trailer' was not found.

at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
--- End of inner exception stack trace ---
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
--- End of inner exception stack trace ---
at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
at Newtonsoft.Json.Linq.JToken.ToObject[T]()
at EmbyStat.Common.Converters.SessionConverter.ConvertToSessions(JArray sessions)+MoveNext() in /EmbyStat.Common/Converters/SessionConverter.cs:line 30
at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at EmbyStat.Services.WebSocketService.WebSocketApiSessionsUpdated(Object sender, GenericEventArgs`1 e) in /EmbyStat.Services/WebSocketService.cs:line 87
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by mregni** [comment]
Looks like I didn't include the trailer enum type. I'll create an update for this.

**Comment by mregni** [comment]
Same issue but for TvChannel

=> https://emby.media/community/index.php?/topic/56640-developing-a-standalone-embystat-server/?p=717047

Note to self: Check Emby code to copy all PlayTypes
