### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by mregni** [mregni/EmbyStat#609]
View details in Rollbar: [https://rollbar.com/UPing/EmbyStat/items/195/](https://rollbar.com/UPing/EmbyStat/items/195/)

```
Traceback (most recent call last):
  File "/EmbyStat.Services/PersonService.cs", line 24, in EmbyStat.Services.PersonService+<GetPersonById>d__3.MoveNext()
  File "System.Runtime.ExceptionServices.ExceptionDispatchInfo", line 12, in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  File "/EmbyStat.Services/MovieService.cs", line 421, in EmbyStat.Services.MovieService+<GetMostFeaturedActorsPerGenre>d__29.MoveNext()
  File "System.Runtime.ExceptionServices.ExceptionDispatchInfo", line 12, in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  File "System.Runtime.CompilerServices.TaskAwaiter", line 46, in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task)
  File "/EmbyStat.Services/MovieService.cs", line 93, in EmbyStat.Services.MovieService+<GetPeopleStatsForCollections>d__9.MoveNext()
  File "System.Runtime.ExceptionServices.ExceptionDispatchInfo", line 12, in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  File "System.Runtime.CompilerServices.TaskAwaiter", line 46, in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task)
  File "/EmbyStat.Controllers/Movie/MovieController.cs", line 44, in EmbyStat.Controllers.Movie.MovieController+<GetPersonStats>d__5.MoveNext()
  File "System.Runtime.ExceptionServices.ExceptionDispatchInfo", line 12, in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  File "System.Runtime.CompilerServices.TaskAwaiter", line 46, in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task)
  File "Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor+<Execute>d__0", line 113, in Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor+<Execute>d__0.MoveNext()
  File "System.Runtime.ExceptionServices.ExceptionDispatchInfo", line 12, in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  File "System.Runtime.CompilerServices.TaskAwaiter", line 46, in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task)
  File "Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__12", line 305, in Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__12.MoveNext()
  File "System.Runtime.ExceptionServices.ExceptionDispatchInfo", line 12, in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  File "Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__10", line 165, in Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__10.MoveNext()
  File "System.Runtime.ExceptionServices.ExceptionDispatchInfo", line 12, in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  File "Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker", line 21, in Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context)
  File "Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker", line 905, in Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted)
  File "Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__13", line 47, in Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__13.MoveNext()
  File "System.Runtime.ExceptionServices.ExceptionDispatchInfo", line 12, in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  File "Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextExceptionFilterAsync>d__24", line 166, in Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextExceptionFilterAsync>d__24.MoveNext()
System.NullReferenceException: Object reference not set to an instance of an object.
```

**Comment by mregni** [comment]
This means that some person is fetched from DB without being it in the DB. But the person is linked to a movie. 

Check how the ID is even known for a movie if the person is not in the DB

**Comment by mregni** [comment]
Looks like it's not fixed
