### ISSUE TITLE
Error when trying to reach people from movies

### ISSUE THREAD

**Issue by hbooo** [mregni/EmbyStat#621]
# Bug report

**Describe the bug**
I have an error when trying to reach movies peoples

**To Reproduce**

1. Have EmbyStat in french
2. Go to movies
3. Go to People
4. Nothing is loaded

**Expected behavior**
People from movies should be loaded

**Screenshots**
![image](https://user-images.githubusercontent.com/242125/55706226-f3d6d580-59e0-11e9-8299-cb3c6c652f9a.png)

**System (please complete the following information):**

- OS: unRaid
- Browser : Chrome
- Version:  uping/embystat:nightly-linux

**Additional context**
`2019-04-08 09:25:08.1736 [INFO] SYSTEM	Booting up server on port 5432 
2019-04-08 09:25:09.5223 [DEBUG] DATABASE-SEEDER	Seeding languages 
2019-04-08 09:25:11.9614 [DEBUG] DATABASE-SEEDER	Seeding Emby status 
2019-04-08 09:25:11.9853 [DEBUG] DATABASE-SEEDER	Seeding job data 
2019-04-08 09:25:12.1891 [INFO] Starting Hangfire Server using job storage: 'Hangfire.MemoryStorage.MemoryStorage' 
2019-04-08 09:25:12.1948 [INFO] Using the following options for Hangfire Server:
    Worker count: 1
    Listening queues: 'main'
    Shutdown timeout: 1.00:00:00
    Schedule polling interval: 00:00:05 
2019-04-08 09:25:12.4360 [INFO] Server main server:123successfully announced in 210.1304 ms 
2019-04-08 09:25:12.4428 [INFO] Server main server:123is starting the registered dispatchers: ServerWatchdog, ServerJobCancellationWatcher, ExpirationManager, CountersAggregator, Worker, DelayedJobScheduler, RecurringJobScheduler... 
2019-04-08 09:25:12.4468 [INFO] Server main server:123all the dispatchers started 
2019-04-08 09:25:13.3463 [INFO] Connecting to ws://mydns:8096/embywebsocket?api_key=xxx&deviceId=yyy
2019-04-08 09:25:13.4443 [INFO] Web socket connection opened. 
2019-04-08 09:25:19.2761 [WARN] The LINQ expression 'where {from CollectionType y in __types_0 where (Convert([y], Int32) == Convert([x].Type, Int32)) select [y] => Any()}' could not be translated and will be evaluated locally. 
2019-04-08 09:25:19.2946 [WARN] The LINQ expression 'where (Convert([y], Int32) == Convert([x].Type, Int32))' could not be translated and will be evaluated locally. 
2019-04-08 09:25:19.3012 [WARN] The LINQ expression 'Any()' could not be translated and will be evaluated locally. 
2019-04-08 09:25:19.7720 [WARN] The Include operation for navigation '[x].ExtraPersons' is unnecessary and was ignored because the navigation is not reachable in the final query results. See https://go.microsoft.com/fwlink/?linkid=850303 for more information. 
2019-04-08 09:25:21.8872 [INFO] EMBY-CLIENT	Sending GET: http://mydns:8096/emby/persons/Frank Welker?SeriesStatuses=&fields=&Filters=&ImageTypes=&AirDays=&EnableImageTypes=&recursive=False&Genres=&StudioIds=&Years=&format=json 
2019-04-08 09:25:22.5099 [WARN] The Include operation for navigation '[x].ExtraPersons' is unnecessary and was ignored because the navigation is not reachable in the final query results. See https://go.microsoft.com/fwlink/?linkid=850303 for more information. 
2019-04-08 09:25:22.8446 [INFO] EMBY-CLIENT	Sending GET: http://mydns:8096/emby/persons/Tim Burton?SeriesStatuses=&fields=&Filters=&ImageTypes=&AirDays=&EnableImageTypes=&recursive=False&Genres=&StudioIds=&Years=&format=json 
2019-04-08 09:25:23.5211 [INFO] EMBY-CLIENT	Sending GET: http://mydns:8096/emby/persons/Anna Akana?SeriesStatuses=&fields=&Filters=&ImageTypes=&AirDays=&EnableImageTypes=&recursive=False&Genres=&StudioIds=&Years=&format=json 
2019-04-08 09:25:24.5620 [WARN] The Include operation for navigation '[x].MediaGenres' is unnecessary and was ignored because the navigation is not reachable in the final query results. See https://go.microsoft.com/fwlink/?linkid=850303 for more information. 
2019-04-08 09:25:24.6681 [INFO] EMBY-CLIENT	Sending GET: http://mydns:8096/emby/persons/Stan Lee?SeriesStatuses=&fields=&Filters=&ImageTypes=&AirDays=&EnableImageTypes=&recursive=False&Genres=&StudioIds=&Years=&format=json 
2019-04-08 09:25:25.1366 [INFO] EMBY-CLIENT	Sending GET: http://mydns:8096/emby/persons/Darby Hawker?SeriesStatuses=&fields=&Filters=&ImageTypes=&AirDays=&EnableImageTypes=&recursive=False&Genres=&StudioIds=&Years=&format=json 
2019-04-08 09:25:25.6057 [INFO] EMBY-CLIENT	Sending GET: http://mydns:8096/emby/persons/Mickie McGowan?SeriesStatuses=&fields=&Filters=&ImageTypes=&AirDays=&EnableImageTypes=&recursive=False&Genres=&StudioIds=&Years=&format=json 
2019-04-08 09:25:26.0891 [INFO] EMBY-CLIENT	Sending GET: http://mydns:8096/emby/persons/Stan Lee?SeriesStatuses=&fields=&Filters=&ImageTypes=&AirDays=&EnableImageTypes=&recursive=False&Genres=&StudioIds=&Years=&format=json 
2019-04-08 09:25:26.5882 [ERROR] An unhandled error occurred. System.NullReferenceException: Object reference not set to an instance of an object.
   at EmbyStat.Services.PersonService.GetPersonById(String id) in /EmbyStat.Services/PersonService.cs:line 24
   at EmbyStat.Services.MovieService.GetMostFeaturedActorsPerGenre(List`1 collectionIds) in /EmbyStat.Services/MovieService.cs:line 421
   at EmbyStat.Services.MovieService.GetPeopleStatsForCollections(List`1 collectionIds) in /EmbyStat.Services/MovieService.cs:line 93
   at EmbyStat.Controllers.Movie.MovieController.GetPersonStats(List`1 collectionIds) in /EmbyStat.Controllers/Movie/MovieController.cs:line 44
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()
`

**Comment by mregni** [comment]
This is linked to #609

**Comment by kesm** [comment]
works with latest version, thanks
