### ISSUE TITLE
Databasa is locked

### ISSUE THREAD

**Issue by jaycedk** [mregni/EmbyStat#645]
# Bug report

**Describe the bug**
Media synchronisation failes, database is locked.
Have tried setting permissions to everyone.
Running as administrator.

**To Reproduce**
Manuel or job

**Expected behavior**
Sync media

**Screenshots**

**System (please complete the following information):**
- Windows 10
- Version [v0.1.0-beta.37]

**Additional context**
2019-04-14 09:09:09.6839 [ERROR] Failed executing DbCommand (30,035ms) [Parameters=[@__sessionId_0='?' (Size = 32)], CommandType='Text', CommandTimeout='30']
SELECT CASE
    WHEN EXISTS (
        SELECT 1
        FROM "Sessions" AS "x"
        WHERE "x"."Id" = @__sessionId_0)
    THEN 1 ELSE 0
END Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
2019-04-14 09:09:09.7256 [ERROR] An exception occurred while iterating over the results of a query for context type 'EmbyStat.Repositories.ApplicationDbContext'.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.GetResult[TResult](IEnumerable`1 valueBuffers, Boolean throwOnNullResult)
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext() Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.GetResult[TResult](IEnumerable`1 valueBuffers, Boolean throwOnNullResult)
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
2019-04-14 09:09:09.7369 [ERROR] An exception occurred while iterating over the results of a query for context type 'EmbyStat.Repositories.ApplicationDbContext'.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.GetResult[TResult](IEnumerable`1 valueBuffers, Boolean throwOnNullResult)
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc) Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.GetResult[TResult](IEnumerable`1 valueBuffers, Boolean throwOnNullResult)
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
2019-04-14 09:09:09.7369 [INFO] Received web socket message: Sessions

**Comment by jaycedk** [comment]
Hmm when i delete til database file, its working again, but then there is no user history.
So it happens when deleting things in the database,
in order til update it self.

**Comment by mregni** [comment]
Problem is that SQLite is very bad in concurrent writes. For every transation, he will always lock the full database instead of the used table/rows.

So I think that there is that you received a session update from Emby while running the media sync job. I'll have to find a way to make room for session updates even when a job is running, maybe just put the sessions in a separate database file.

**Comment by jaycedk** [comment]
Ok thanks for the info :)
Happy bug squashing :)

**Comment by jaycedk** [comment]
Hmm having a look at the finish time of the Full sync. for my folder size, it takes about 5-6 hours to complete. So right now I will try to set the small sync to 12:00 local time

**Comment by jaycedk** [comment]
LOL ok guess I can't change that.
The save butten do not work.
The setting is reverting back to standard.

**Comment by mregni** [comment]
Mmmm, that is strange that it takes 5 mintes to sync. Have to check how Hangfire handles the job settings!

Seems like a lot more people having problems with database locks, should try to maybe switch to a different db system.

**Comment by jaycedk** [comment]
I will update you tomorrow, when i see if the changes to the scheduled jobs, worked.

**Comment by jaycedk** [comment]
OK switched small sync, back to the original time, it was, for me , the DB cleanup. that scrued the puch.
Running on top of the daily update, is not greate.

**Comment by PartTheSeas** [comment]
I have exactly the same error on my windows machine. Log is totally the same. The initial media sync works great, the 2nd doesn't anymore. Dayum!

**Comment by mregni** [comment]
I'm ready to release a new version with LiteDB. So the database issue might be fixed as well.

**Comment by jaycedk** [comment]
Super :) looking forward to testing.

**Comment by mregni** [comment]
I pushed a new beta version 0.2.0-beta.1 today. Give it a spin and see if it's working for you. Normally there shouldn't be any database locks anymore after the move to LiteDB

**Comment by mregni** [comment]
Does someone still have database lock issues? This normally should not happen anymore.
If not, I'll close the issue.

**Comment by mregni** [comment]
Does someone still have database lock issues? This normally should not happen anymore.
If not, I'll close the issue.

**Comment by jaycedk** [comment]
I have had no lockups, since the new release.

**Comment by jaycedk** [comment]
So lets close this :)

**Comment by mregni** [comment]
@all-contributors add jaycedk for userTesting, bug
@all-contributors add Happy2Play for userTesting, bug
@all-contributors add Diedrich for userTesting, bug
@all-contributors add adrianwi for userTesting, bug

**Comment by mregni** [comment]
@all-contributors add jaycedk for userTesting, bug
