### ISSUE TITLE
Can't login to Emby anymore

### ISSUE THREAD

**Issue by mregni** [mregni/EmbyStat#789]
Looks like something broke the Emby login flow in the wizard (settings is affected as well probably)
```
2019-07-18 14:17:34.1542 [INFO] EMBY-CLIENT	Sending POST: https://reggi.ddns.net:8097/emby/Users/AuthenticateByName?format=json 
2019-07-18 14:17:34.3953 [ERROR] EMBY-CLIENT	Call to Emby failed MediaBrowser.Model.Net.HttpException: One or more errors occurred. (The remote server returned an error: (400) Bad Request.) ---> System.AggregateException: One or more errors occurred. (The remote server returned an error: (400) Bad Request.) ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at EmbyStat.Common.Net.HttpWebRequestClient.GetResponse(HttpRequest options, Boolean sendFailureResponse) in d:\a\1\s\EmbyStat.Common\Net\HttpWebRequestClient.cs:line 54
   --- End of inner exception stack trace ---
   at EmbyStat.Common.Net.HttpWebRequestClient.GetResponse(HttpRequest options, Boolean sendFailureResponse) in d:\a\1\s\EmbyStat.Common\Net\HttpWebRequestClient.cs:line 80
   at EmbyStat.Common.Net.HttpWebRequestClient.SendAsync(HttpRequest options) in d:\a\1\s\EmbyStat.Common\Net\HttpWebRequestClient.cs:line 116
   at EmbyStat.Clients.Emby.Http.BaseClient.SendAsync(HttpRequest request) in d:\a\1\s\EmbyStat.Clients.Emby.Http\BaseClient.cs:line 268
   at EmbyStat.Clients.Emby.Http.BaseClient.PostAsync[T](String url, Dictionary`2 args, CancellationToken cancellationToken) in d:\a\1\s\EmbyStat.Clients.Emby.Http\BaseClient.cs:line 180
2019-07-18 14:17:34.4194 [WARN] SERVER-API	Username or password are wrong, user should try again with other credentials! 
2019-07-18 14:17:34.4194 [ERROR] MediaBrowser.Model.Net.HttpException: One or more errors occurred. (The remote server returned an error: (400) Bad Request.) ---> System.AggregateException: One or more errors occurred. (The remote server returned an error: (400) Bad Request.) ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at EmbyStat.Common.Net.HttpWebRequestClient.GetResponse(HttpRequest options, Boolean sendFailureResponse) in d:\a\1\s\EmbyStat.Common\Net\HttpWebRequestClient.cs:line 54
   --- End of inner exception stack trace ---
   at EmbyStat.Common.Net.HttpWebRequestClient.GetResponse(HttpRequest options, Boolean sendFailureResponse) in d:\a\1\s\EmbyStat.Common\Net\HttpWebRequestClient.cs:line 80
   at EmbyStat.Common.Net.HttpWebRequestClient.SendAsync(HttpRequest options) in d:\a\1\s\EmbyStat.Common\Net\HttpWebRequestClient.cs:line 116
   at EmbyStat.Clients.Emby.Http.BaseClient.SendAsync(HttpRequest request) in d:\a\1\s\EmbyStat.Clients.Emby.Http\BaseClient.cs:line 268
   at EmbyStat.Clients.Emby.Http.BaseClient.PostAsync[T](String url, Dictionary`2 args, CancellationToken cancellationToken) in d:\a\1\s\EmbyStat.Clients.Emby.Http\BaseClient.cs:line 180 MediaBrowser.Model.Net.HttpException: One or more errors occurred. (The remote server returned an error: (400) Bad Request.) ---> System.AggregateException: One or more errors occurred. (The remote server returned an error: (400) Bad Request.) ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at EmbyStat.Common.Net.HttpWebRequestClient.GetResponse(HttpRequest options, Boolean sendFailureResponse) in d:\a\1\s\EmbyStat.Common\Net\HttpWebRequestClient.cs:line 54
   --- End of inner exception stack trace ---
   at EmbyStat.Common.Net.HttpWebRequestClient.GetResponse(HttpRequest options, Boolean sendFailureResponse) in d:\a\1\s\EmbyStat.Common\Net\HttpWebRequestClient.cs:line 80
   at EmbyStat.Common.Net.HttpWebRequestClient.SendAsync(HttpRequest options) in d:\a\1\s\EmbyStat.Common\Net\HttpWebRequestClient.cs:line 116
   at EmbyStat.Clients.Emby.Http.BaseClient.SendAsync(HttpRequest request) in d:\a\1\s\EmbyStat.Clients.Emby.Http\BaseClient.cs:line 268
   at EmbyStat.Clients.Emby.Http.BaseClient.PostAsync[T](String url, Dictionary`2 args, CancellationToken cancellationToken) in d:\a\1\s\EmbyStat.Clients.Emby.Http\BaseClient.cs:line 180
2019-07-18 14:17:34.4353 [WARN] EXCEPTION-HANDLER	Application thrown error: TOKEN_FAILED 
2019-07-18 14:17:34.4353 [WARN] EXCEPTION-HANDLER	Frontend will know what to do with this! ```

**Comment by mregni** [comment]
Fixed
