### ISSUE TITLE
Log page throws exception on open

### ISSUE THREAD

**Issue by mregni** [mregni/EmbyStat#810]
Seems that I missed some mappings

```019-07-21 01:53:14.0480 [ERROR] An unhandled error occurred. AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
List`1 -> IList`1
System.Collections.Generic.List`1[[EmbyStat.Services.Models.Logs.LogFile, EmbyStat.Services, Version=0.2.0.3, Culture=neutral, PublicKeyToken=null]] -> System.Collections.Generic.IList`1[[EmbyStat.Controllers.Log.LogFileViewModel, EmbyStat.Controllers, Version=0.2.0.3, Culture=neutral, PublicKeyToken=null]] ---> AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.

Mapping types:
LogFile -> LogFileViewModel
EmbyStat.Services.Models.Logs.LogFile -> EmbyStat.Controllers.Log.LogFileViewModel
   at lambda_method(Closure , LogFile , LogFileViewModel , ResolutionContext )
   at AutoMapper.Mapper.AutoMapper.IRuntimeMapper.Map[TSource,TDestination](TSource source, TDestination destination, ResolutionContext context, IMemberMap memberMap)
   at lambda_method(Closure , List`1 , IList`1 , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , List`1 , IList`1 , ResolutionContext )
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source)
   at EmbyStat.Controllers.Log.LogController.GetLogFileList() in d:\a\1\s\EmbyStat.Controllers\Log\LogController.cs:line 26
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()```

**Comment by mregni** [comment]
Should be fixed
