### ISSUE TITLE
Issue with initial Authentication

### ISSUE THREAD

**Issue by trizzone52** [mregni/EmbyStat#813]
# Bug report

**Describe the bug**
When running the setup wizard, I am stuck at "EmbyStat is an Emby administrator" check. It pops up with "Getting Emby token failed. Please check your credentials and domain/ip address."

**To Reproduce**

1. Re-installation
2. Select any user 
3. Enter info to connnect to server (Emby 4.2.0.33 is running on linux, EmbyStat has issue on when it runs on both windows and linux)
4. See bug on when attempting first sync

**Expected behavior**
Expects I should be able to Sync with Emby after imputing the correct username/password/address

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/1944815/61658958-13da8e00-ac8c-11e9-87bd-96bd4e33d3a9.jpg)

**System (please complete the following information):**

- OS: Emby on Linux, EmbyStat on windows or linux (others untested)
- Browser Chrome
- EmbyStat 0.2.0-beta4
- Emby 4.2.0.33

**Additional context**
Not sure if it's an issue with Emby or EmbyStat. 
I am using a custom SSL certificate, but don't think that's the problem.
Happens with both http and https connection to Emby.
I did get a connection once, then update/re-installed and wasn't able to get another connection. 

Emby Log:
2019-07-22 13:41:13.783 Info HttpServer: HTTP POST https://xxxx.xxx:xxxx/emby/Users/AuthenticateByName?format=json. UserAgent: 
2019-07-22 13:41:13.784 Info UserManager: Authentication request for EmbyStat has succeeded.
2019-07-22 13:41:13.784 Info SessionManager: Reissuing access token: xxxxxxxxxxxxxxx
2019-07-22 13:41:13.786 Error HttpServer: Error processing request
	*** Error Report ***
	Version: 4.2.0.33
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
	Operating system: Unix 4.19.0.5
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Runtime: file:///opt/emby-server/system/System.Private.CoreLib.dll
	Processor count: 8
	Program data path: /var/lib/emby
	Application directory: /opt/emby-server/system
	System.ArgumentNullException: System.ArgumentNullException: Value cannot be null.
	Parameter name: appName
	   at Emby.Server.Implementations.Session.SessionManager.LogSessionActivity(String appName, String appVersion, String deviceId, String deviceName, String remoteEndPoint, User user)
	   at Emby.Server.Implementations.Session.SessionManager.AuthenticateNewSessionInternal(AuthenticationRequest request, Boolean enforcePassword, CancellationToken cancellationToken)
	   at MediaBrowser.Api.UserService.Post(AuthenticateUserByName request)
	   at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 host, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: Emby.Server.Implementations
	TargetSite: MediaBrowser.Controller.Session.SessionInfo LogSessionActivity(System.String, System.String, System.String, System.String, System.String, MediaBrowser.Controller.Entities.User)
	
2019-07-22 13:41:13.786 Info HttpServer: HTTP Response 400 to 192.168.0.1. Time: 3ms. https://xxxx.xxx:xxxx/emby/Users/AuthenticateByName?format=json
2019-07-22 13:41:21.245 Info HttpServer: HTTP GET https://xxxx.xxx:xxxx/emby/ScheduledTasks?IsEnabled=true. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.62 Safari/537.36
2

EmbyStat Log:
2019-07-22 14:04:47.8052 [INFO] EMBY-CLIENT     Sending POST: https://xxxx.xxx:xxxx/emby/Users/AuthenticateByName?format=json
2019-07-22 14:04:47.8883 [ERROR] EMBY-CLIENT    Call to Emby failed MediaBrowser.Model.Net.HttpException: One or more errors occurred. (The remote server returned an error: (400) Bad Request.) ---> System.AggregateException: One or more errors occurred. (The remote server returned an error: (400) Bad Request.) ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at EmbyStat.Common.Net.HttpWebRequestClient.GetResponse(HttpRequest options, Boolean sendFailureResponse) in C:\Users\Trizz\Desktop\Work\EmbyStat\EmbyStat.Common\Net\HttpWebRequestClient.cs:line 54
   --- End of inner exception stack trace ---
   at EmbyStat.Common.Net.HttpWebRequestClient.GetResponse(HttpRequest options, Boolean sendFailureResponse) in C:\Users\Trizz\Desktop\Work\EmbyStat\EmbyStat.Common\Net\HttpWebRequestClient.cs:line 88
   at EmbyStat.Common.Net.HttpWebRequestClient.SendAsync(HttpRequest options) in C:\Users\Trizz\Desktop\Work\EmbyStat\EmbyStat.Common\Net\HttpWebRequestClient.cs:line 124
   at EmbyStat.Clients.Emby.Http.BaseClient.SendAsync(HttpRequest request) in C:\Users\Trizz\Desktop\EmbyStat\EmbyStat.Clients.Emby.Http\BaseClient.cs:line 274
   at EmbyStat.Clients.Emby.Http.BaseClient.PostAsync[T](String url, Dictionary`2 args, CancellationToken cancellationToken) in C:\Users\Trizz\Desktop\EmbyStat\EmbyStat.Clients.Emby.Http\BaseClient.cs:line 186
2019-07-22 14:04:47.8883 [ERROR] EmbyStat.Common.Exceptions.BusinessException: EMBY_CALL_FAILED ---> MediaBrowser.Model.Net.HttpException: One or more errors occurred. (The remote server returned an error: (400) Bad Request.) ---> System.AggregateException: One or more errors occurred. (The remote server returned an error: (400) Bad Request.) ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at EmbyStat.Common.Net.HttpWebRequestClient.GetResponse(HttpRequest options, Boolean sendFailureResponse) in C:\Users\Trizz\Desktop\Work\EmbyStat\EmbyStat.Common\Net\HttpWebRequestClient.cs:line 54
   --- End of inner exception stack trace ---
   at EmbyStat.Common.Net.HttpWebRequestClient.GetResponse(HttpRequest options, Boolean sendFailureResponse) in C:\Users\Trizz\Desktop\Work\EmbyStat\EmbyStat.Common\Net\HttpWebRequestClient.cs:line 88
   at EmbyStat.Common.Net.HttpWebRequestClient.SendAsync(HttpRequest options) in C:\Users\Trizz\Desktop\Work\EmbyStat\EmbyStat.Common\Net\HttpWebRequestClient.cs:line 124
   at EmbyStat.Clients.Emby.Http.BaseClient.SendAsync(HttpRequest request) in C:\Users\Trizz\Desktop\EmbyStat\EmbyStat.Clients.Emby.Http\BaseClient.cs:line 274
   at EmbyStat.Clients.Emby.Http.BaseClient.PostAsync[T](String url, Dictionary`2 args, CancellationToken cancellationToken) in C:\Users\Trizz\Desktop\EmbyStat\EmbyStat.Clients.Emby.Http\BaseClient.cs:line 186
   --- End of inner exception stack trace ---
   at EmbyStat.Clients.Emby.Http.BaseClient.PostAsync[T](String url, Dictionary`2 args, CancellationToken cancellationToken) in C:\Users\Trizz\Desktop\EmbyStat\EmbyStat.Clients.Emby.Http\BaseClient.cs:line 202
   at EmbyStat.Clients.Emby.Http.EmbyClient.AuthenticateUserAsync(String username, String password, String address) in C:\Users\Trizz\Desktop\EmbyStat\EmbyStat.Clients.Emby.Http\EmbyClient.cs:line 71
   at EmbyStat.Services.EmbyService.GetEmbyToken(EmbyLogin login) in C:\Users\Trizz\Desktop\EmbyStat\EmbyStat.Services\EmbyService.cs:line 99 EmbyStat.Common.Exceptions.BusinessException: EMBY_CALL_FAILED ---> MediaBrowser.Model.Net.HttpException: One or more errors occurred. (The remote server returned an error: (400) Bad Request.) ---> System.AggregateException: One or more errors occurred. (The remote server returned an error: (400) Bad Request.) ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at EmbyStat.Common.Net.HttpWebRequestClient.GetResponse(HttpRequest options, Boolean sendFailureResponse) in C:\Users\Trizz\Desktop\Work\EmbyStat\EmbyStat.Common\Net\HttpWebRequestClient.cs:line 54
   --- End of inner exception stack trace ---
   at EmbyStat.Common.Net.HttpWebRequestClient.GetResponse(HttpRequest options, Boolean sendFailureResponse) in C:\Users\Trizz\Desktop\Work\EmbyStat\EmbyStat.Common\Net\HttpWebRequestClient.cs:line 88
   at EmbyStat.Common.Net.HttpWebRequestClient.SendAsync(HttpRequest options) in C:\Users\Trizz\Desktop\Work\EmbyStat\EmbyStat.Common\Net\HttpWebRequestClient.cs:line 124
   at EmbyStat.Clients.Emby.Http.BaseClient.SendAsync(HttpRequest request) in C:\Users\Trizz\Desktop\EmbyStat\EmbyStat.Clients.Emby.Http\BaseClient.cs:line 274
   at EmbyStat.Clients.Emby.Http.BaseClient.PostAsync[T](String url, Dictionary`2 args, CancellationToken cancellationToken) in C:\Users\Trizz\Desktop\EmbyStat\EmbyStat.Clients.Emby.Http\BaseClient.cs:line 186
   --- End of inner exception stack trace ---
   at EmbyStat.Clients.Emby.Http.BaseClient.PostAsync[T](String url, Dictionary`2 args, CancellationToken cancellationToken) in C:\Users\Trizz\Desktop\EmbyStat\EmbyStat.Clients.Emby.Http\BaseClient.cs:line 202
   at EmbyStat.Clients.Emby.Http.EmbyClient.AuthenticateUserAsync(String username, String password, String address) in C:\Users\Trizz\Desktop\EmbyStat\EmbyStat.Clients.Emby.Http\EmbyClient.cs:line 71
   at EmbyStat.Services.EmbyService.GetEmbyToken(EmbyLogin login) in C:\Users\Trizz\Desktop\EmbyStat\EmbyStat.Services\EmbyService.cs:line 99
2019-07-22 14:04:47.8921 [WARN] SERVER-API      Username or password are wrong, user should try again with other credentials!
2019-07-22 14:04:47.8921 [ERROR] MediaBrowser.Model.Net.HttpException: One or more errors occurred. (The remote server returned an error: (400) Bad Request.) ---> System.AggregateException: One or more errors occurred. (The remote server returned an error: (400) Bad Request.) ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at EmbyStat.Common.Net.HttpWebRequestClient.GetResponse(HttpRequest options, Boolean sendFailureResponse) in C:\Users\Trizz\Desktop\Work\EmbyStat\EmbyStat.Common\Net\HttpWebRequestClient.cs:line 54
   --- End of inner exception stack trace ---
   at EmbyStat.Common.Net.HttpWebRequestClient.GetResponse(HttpRequest options, Boolean sendFailureResponse) in C:\Users\Trizz\Desktop\Work\EmbyStat\EmbyStat.Common\Net\HttpWebRequestClient.cs:line 88
   at EmbyStat.Common.Net.HttpWebRequestClient.SendAsync(HttpRequest options) in C:\Users\Trizz\Desktop\Work\EmbyStat\EmbyStat.Common\Net\HttpWebRequestClient.cs:line 124
   at EmbyStat.Clients.Emby.Http.BaseClient.SendAsync(HttpRequest request) in C:\Users\Trizz\Desktop\EmbyStat\EmbyStat.Clients.Emby.Http\BaseClient.cs:line 274
   at EmbyStat.Clients.Emby.Http.BaseClient.PostAsync[T](String url, Dictionary`2 args, CancellationToken cancellationToken) in C:\Users\Trizz\Desktop\EmbyStat\EmbyStat.Clients.Emby.Http\BaseClient.cs:line 186 MediaBrowser.Model.Net.HttpException: One or more errors occurred. (The remote server returned an error: (400) Bad Request.) ---> System.AggregateException: One or more errors occurred. (The remote server returned an error: (400) Bad Request.) ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at EmbyStat.Common.Net.HttpWebRequestClient.GetResponse(HttpRequest options, Boolean sendFailureResponse) in C:\Users\Trizz\Desktop\Work\EmbyStat\EmbyStat.Common\Net\HttpWebRequestClient.cs:line 54
   --- End of inner exception stack trace ---
   at EmbyStat.Common.Net.HttpWebRequestClient.GetResponse(HttpRequest options, Boolean sendFailureResponse) in C:\Users\Trizz\Desktop\Work\EmbyStat\EmbyStat.Common\Net\HttpWebRequestClient.cs:line 88
   at EmbyStat.Common.Net.HttpWebRequestClient.SendAsync(HttpRequest options) in C:\Users\Trizz\Desktop\Work\EmbyStat\EmbyStat.Common\Net\HttpWebRequestClient.cs:line 124
   at EmbyStat.Clients.Emby.Http.BaseClient.SendAsync(HttpRequest request) in C:\Users\Trizz\Desktop\EmbyStat\EmbyStat.Clients.Emby.Http\BaseClient.cs:line 274
   at EmbyStat.Clients.Emby.Http.BaseClient.PostAsync[T](String url, Dictionary`2 args, CancellationToken cancellationToken) in C:\Users\Trizz\Desktop\EmbyStat\EmbyStat.Clients.Emby.Http\BaseClient.cs:line 186
2019-07-22 14:04:47.8949 [WARN] EXCEPTION-HANDLER       Application thrown error: TOKEN_FAILED
2019-07-22 14:04:47.8949 [WARN] EXCEPTION-HANDLER       Frontend will know what to do with this!

**Comment by mregni** [comment]
Looking at your logs it seems that indeed EmbyStat is doing something strange with the login call as Emby is successfully sending a token back.

I have a look at the response of your server version, maybe they changed something! My server version is still 4.1.1.0

Ow, I also edited your post. I removed all links to your domain.

**Comment by trizzone52** [comment]
Thank you much for the editing help! I'm still learning.
I could very well see this being an issue with the Emby Beta branch I'm using.  May be a potential issue to head off, more than a bug.

**Comment by mregni** [comment]
Yeah, I presume that they updated something that is not yet in the stable train. 
So I will need to fix it but only after Emby pushed his update to a stable release. Otherwise, nothing will work anymore. 

I'll have to figure out something to keep parallel development between Emby and EmbyStat so I don't get any problems like this in the future.

**Comment by trizzone52** [comment]
I decided to try the blind fix of deleting the usersettings.json file, and the wizard then worked just fine.  

I'm guessing the issue originated when I had previously set up a session with an incorrect installation. Therefore, when I was connecting with the currently installation it was simply re-issuing an invalid token.  Deleting my usersettings.json caused EmbyStat to generate a new "Id" value, leading to Emby creating a new token instead of re-issuing the old one.

Note: I had been having file permissions errors and partial copy issues during the erroneous install that likely create my error state.

**Comment by mregni** [comment]
I'm creating a new beta version today with some fixes for the new Emby release (4.2.0.40). On what OS do you run EmbyStat? I haven't had the time to create install/run scripts for Unix systems or Windows.

**Comment by trizzone52** [comment]
I received the error on both windows 10 and debian buster.  I was alternating between official releases and personal builds in the same folder and then syncing it between Windows and Debian with the program Syncthing. That crazy setup was what likely caused the original issue. Then having the same config file between both windows and debian allowed me to have the same issue on both OS's once I stepped back and installed more carefully.

**Comment by mregni** [comment]
You still have issues with the authentication with the new releases? If not, I'll close the ticket.

**Comment by trizzone52** [comment]
We can close this ticket.  Issue has been solved on my machine, and I haven't been able to replicate the issue.

**Comment by mregni** [comment]
Thanks man!! Good to know it fixed itself :D
