### ISSUE TITLE
NotImplementedException on db cleanup job

### ISSUE THREAD

**Issue by mregni** [mregni/EmbyStat#835]
NotImplementedException on db cleanup job. woeps

```
2019-07-29 23:02:29.6379 [ERROR] Error while running job System.NotImplementedException: The method or operation is not implemented.
   at EmbyStat.Repositories.StatisticsRepository.CleanupStatistics() in d:\a\1\s\EmbyStat.Repositories\StatisticsRepository.cs:line 54
   at EmbyStat.Jobs.Jobs.Maintenance.DatabaseCleanupJob.RunJobAsync() in d:\a\1\s\EmbyStat.Jobs\Jobs\Maintenance\DatabaseCleanupJob.cs:line 33
   at EmbyStat.Jobs.BaseJob.Execute() in d:\a\1\s\EmbyStat.Jobs\BaseJob.cs:line 46
2019-07-29 23:02:29.6528 [ERROR] DATABASE CLEANUP-JOB	Job failed, check logs for more info. 
2019-07-29 23:02:29.6528 [WARN] Failed to process the job '6209afee-5362-40ed-a3af-1887cb6dc70e': an exception occurred. Retry attempt 2 of 2 will be performed in 00:00:56. System.NotImplementedException: The method or operation is not implemented.
   at EmbyStat.Repositories.StatisticsRepository.CleanupStatistics() in d:\a\1\s\EmbyStat.Repositories\StatisticsRepository.cs:line 54
   at EmbyStat.Jobs.Jobs.Maintenance.DatabaseCleanupJob.RunJobAsync() in d:\a\1\s\EmbyStat.Jobs\Jobs\Maintenance\DatabaseCleanupJob.cs:line 33
   at EmbyStat.Jobs.BaseJob.Execute() in d:\a\1\s\EmbyStat.Jobs\BaseJob.cs:line 46
   at EmbyStat.Jobs.BaseJob.Execute() in d:\a\1\s\EmbyStat.Jobs\BaseJob.cs:line 58
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by mregni** [comment]
We need to stop syncing all actors from Emby, we don't need them anyway.
Just sync the ones that we need when calculating the statistics

**Comment by mregni** [comment]
@all-contributors add Happy2Play for userTesting, bug

**Comment by mregni** [comment]
@all-contributors add Happy2Play for userTesting, bug

**Comment by mregni** [comment]
@all-contributors add Diedrich for userTesting, bug

**Comment by mregni** [comment]
@all-contributors add adrianwi for userTesting, bug

**Comment by mregni** [comment]
@all-contributors add gerritv for userTesting, bug
