### ISSUE TITLE
System.InvalidCastException: Unable to cast object of type 'LiteDB.DataPage' to type 'LiteDB.IndexPage'

### ISSUE THREAD

**Issue by brazerZa** [mregni/EmbyStat#959]
Hi.

EmbyStart runs fine for 2 or 3 days and the suddenly throws this exception. Can do Sync any more and stats for movies and show are not working.

[2019-10-09.log](https://github.com/mregni/EmbyStat/files/3708597/2019-10-09.log)

**Comment by brazerZa** [comment]
This was fixed with beta 15

**Comment by brazerZa** [comment]
Damn...Its back

2020-01-24 00:00:02.6479 [ERROR] Error in event handler System.InvalidCastException: Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.HeaderPage'.
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.TransactionService.PersistDirtyPages()
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.InsertBulk(String collection, IEnumerable`1 docs, Int32 batchSize, BsonType autoId)
   at EmbyStat.Repositories.SessionRepository.<>c__DisplayClass5_0.<InsertPlays>b__0() in d:\a\1\s\EmbyStat.Repositories\SessionRepository.cs:line 72
   at EmbyStat.Repositories.BaseRepository.ExecuteQuery(Action query) in d:\a\1\s\EmbyStat.Repositories\BaseRepository.cs:line 29
   at EmbyStat.Services.SessionService.ProcessSessions(List`1 sessions) in d:\a\1\s\EmbyStat.Services\SessionService.cs:line 46
   at EmbyStat.Services.WebSocketService.WebSocketApiSessionsUpdated(Object sender, GenericEventArgs`1 e) in d:\a\1\s\EmbyStat.Services\WebSocketService.cs:line 107
   at EmbyStat.Clients.Emby.WebSocket.WebSocketApi.FireEvent[T](EventHandler`1 handler, Object sender, T args) in d:\a\1\s\EmbyStat.Clients.Emby.WebSocket\WebSocketApi.cs:line 212

**Comment by SkalCore** [comment]
same here:

disable my series so that only movies synced. Worked for one day, now this happend:

2020-02-28 20:31:05.2056 [ERROR] Error while running job System.InvalidCastException: Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.IndexPage'.
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.IndexService.Delete(CollectionIndex index, PageAddress nodeAddress)
   at LiteDB.LiteEngine.<>c__DisplayClass8_0.<Delete>b__0(CollectionPage col)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at EmbyStat.Repositories.ShowRepository.<>c__DisplayClass2_0.<RemoveShowsThatAreNotUpdated>b__0() in d:\a\1\s\EmbyStat.Repositories\ShowRepository.cs:line 45
   at EmbyStat.Repositories.BaseRepository.ExecuteQuery(Action query) in d:\a\1\s\EmbyStat.Repositories\BaseRepository.cs:line 29
   at EmbyStat.Repositories.ShowRepository.RemoveShowsThatAreNotUpdated(DateTime startTime) in d:\a\1\s\EmbyStat.Repositories\ShowRepository.cs:line 49
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessShowsAsync(IEnumerable`1 libraries, CancellationToken cancellationToken) in d:\a\1\s\EmbyStat.Jobs\Jobs\Sync\MediaSyncJob.cs:line 206
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync() in d:\a\1\s\EmbyStat.Jobs\Jobs\Sync\MediaSyncJob.cs:line 85
   at EmbyStat.Jobs.BaseJob.Execute() in d:\a\1\s\EmbyStat.Jobs\BaseJob.cs:line 54
2020-02-28 20:31:05.2583 [ERROR] MEDIASYNC-JOB	Job failed, check logs for more info. 
2020-02-28 20:31:05.7627 [WARN] Failed to process the job '7002c4e4-b92c-4470-81f4-6e28c9b597e4': an exception occurred. Retry attempt 1 of 2 will be performed in 00:00:37. System.InvalidCastException: Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.IndexPage'.
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.IndexService.Delete(CollectionIndex index, PageAddress nodeAddress)
   at LiteDB.LiteEngine.<>c__DisplayClass8_0.<Delete>b__0(CollectionPage col)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at EmbyStat.Repositories.ShowRepository.<>c__DisplayClass2_0.<RemoveShowsThatAreNotUpdated>b__0() in d:\a\1\s\EmbyStat.Repositories\ShowRepository.cs:line 45
   at EmbyStat.Repositories.BaseRepository.ExecuteQuery(Action query) in d:\a\1\s\EmbyStat.Repositories\BaseRepository.cs:line 29
   at EmbyStat.Repositories.ShowRepository.RemoveShowsThatAreNotUpdated(DateTime startTime) in d:\a\1\s\EmbyStat.Repositories\ShowRepository.cs:line 49
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessShowsAsync(IEnumerable`1 libraries, CancellationToken cancellationToken) in d:\a\1\s\EmbyStat.Jobs\Jobs\Sync\MediaSyncJob.cs:line 206
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync() in d:\a\1\s\EmbyStat.Jobs\Jobs\Sync\MediaSyncJob.cs:line 85
   at EmbyStat.Jobs.BaseJob.Execute() in d:\a\1\s\EmbyStat.Jobs\BaseJob.cs:line 54
   at EmbyStat.Jobs.BaseJob.Execute() in d:\a\1\s\EmbyStat.Jobs\BaseJob.cs:line 66
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by mregni** [comment]
I updated to LiteDB V5, can you please check if the problem is still there? (A clean install of beta.18 is needed for this to work)
