### ISSUE TITLE
Media synchronisation fails, Sequence contains more than one matching element

### ISSUE THREAD

**Issue by phdelodder** [mregni/EmbyStat#969]
# Bug report

**Describe the bug**
```
2019-11-01 05:49:02.2653 [ERROR] Error while running job System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at EmbyStat.Common.Extensions.ShowExtension.GetNonSpecialEpisodeCount(Show show, Boolean includeMissing) in d:\a\1\s\EmbyStat.Common\Extensions\ShowExtension.cs:line 16
   at System.Linq.Enumerable.Sum[TSource](IEnumerable`1 source, Func`2 selector)
   at EmbyStat.Services.ShowService.TotalEpisodeCount(IReadOnlyList`1 shows) in d:\a\1\s\EmbyStat.Services\ShowService.cs:line 401
   at EmbyStat.Services.ShowService.CalculateGeneralStatistics(IReadOnlyList`1 shows) in d:\a\1\s\EmbyStat.Services\ShowService.cs:line 77
   at EmbyStat.Services.ShowService.CalculateShowStatistics(List`1 libraryIds) in d:\a\1\s\EmbyStat.Services\ShowService.cs:line 62
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.CalculateStatistics() in d:\a\1\s\EmbyStat.Jobs\Jobs\Sync\MediaSyncJob.cs:line 394
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync() in d:\a\1\s\EmbyStat.Jobs\Jobs\Sync\MediaSyncJob.cs:line 93
   at EmbyStat.Jobs.BaseJob.Execute() in d:\a\1\s\EmbyStat.Jobs\BaseJob.cs:line 54
2019-11-01 05:49:02.2653 [ERROR] MEDIASYNC-JOB	Job failed, check logs for more info. 
2019-11-01 05:49:02.2653 [ERROR] Failed to process the job '7d064350-574f-4575-8ba1-e01418b5e3b1': an exception occurred. System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at EmbyStat.Common.Extensions.ShowExtension.GetNonSpecialEpisodeCount(Show show, Boolean includeMissing) in d:\a\1\s\EmbyStat.Common\Extensions\ShowExtension.cs:line 16
   at System.Linq.Enumerable.Sum[TSource](IEnumerable`1 source, Func`2 selector)
   at EmbyStat.Services.ShowService.TotalEpisodeCount(IReadOnlyList`1 shows) in d:\a\1\s\EmbyStat.Services\ShowService.cs:line 401
   at EmbyStat.Services.ShowService.CalculateGeneralStatistics(IReadOnlyList`1 shows) in d:\a\1\s\EmbyStat.Services\ShowService.cs:line 77
   at EmbyStat.Services.ShowService.CalculateShowStatistics(List`1 libraryIds) in d:\a\1\s\EmbyStat.Services\ShowService.cs:line 62
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.CalculateStatistics() in d:\a\1\s\EmbyStat.Jobs\Jobs\Sync\MediaSyncJob.cs:line 394
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync() in d:\a\1\s\EmbyStat.Jobs\Jobs\Sync\MediaSyncJob.cs:line 93
   at EmbyStat.Jobs.BaseJob.Execute() in d:\a\1\s\EmbyStat.Jobs\BaseJob.cs:line 54
   at EmbyStat.Jobs.BaseJob.Execute() in d:\a\1\s\EmbyStat.Jobs\BaseJob.cs:line 66
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**To Reproduce**

1. Go to 'Jobs'
2. Click on 'Media synchronisation'

**Expected behavior**

**Screenshots**

**System (please complete the following information):**

EmbyStat version: 0.2.0-beta.12
Operating system: debian x64 9

**Additional context**

**Comment by mregni** [comment]
Oke, this is a very weird exception because I don't do a SingleOrDefault() anywhere near those lines. Anyway, I'll have a look at it.

I did already refactor a lot of that code so it could be already fixed in the new upcoming release soon.

**Comment by phdelodder** [comment]
With version v0.2.1-dev.424 it seems to be working.
