### ISSUE TITLE
Media synchronisation fails.

### ISSUE THREAD

**Issue by sbcrumb** [mregni/EmbyStat#978]
# Bug report

**Describe the bug**
Media Sync Fails repeatedly. 

**To Reproduce**
Sync Media manual or the job.

**Expected behavior**
I expect it to sync.

**Screenshots**
None

**System (please complete the following information):**

- OS: [e.g. Windows, Ubuntu]
Ubuntu 18.04
Chrome (latest)

**Additional context**
See logs
[https://hatebin.com/oesgbmjtyk](url)

**Comment by mregni** [comment]
Hey @sbcrumb, thanks for your bug report.
Can you please retry with the new version I just release since I removed a lot of the custom HTTP web request code and switched to RestSharp for handling all HTTP requests.

**Comment by jaycedk** [comment]
Hi im also seeing some sync errors.
Im on EmbyStat version: 0.2.0-beta.13
Its probably my own doing i moves some shows to a different folder.
2019-11-13 18:16:55.6020 [ERROR] Error while running job LiteDB.LiteException: Cannot insert duplicate key in unique index '_id'. The duplicate value is '145990'.
   at LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, Byte level, IndexNode last)
   at LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, IndexNode last)
   at LiteDB.LiteEngine.InsertDocument(CollectionPage col, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteEngine.<>c__DisplayClass22_0.<Insert>b__0(CollectionPage col)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.InsertBulk(String collection, IEnumerable`1 docs, Int32 batchSize, BsonType autoId)
   at LiteDB.LiteCollection`1.InsertBulk(IEnumerable`1 docs, Int32 batchSize)
   at EmbyStat.Repositories.ShowRepository.<>c__DisplayClass5_0.<UpsertShow>b__0() in d:\a\1\s\EmbyStat.Repositories\ShowRepository.cs:line 90
   at EmbyStat.Repositories.BaseRepository.ExecuteQuery(Action query) in d:\a\1\s\EmbyStat.Repositories\BaseRepository.cs:line 29
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.PerformShowSyncAsync(IReadOnlyList`1 showsThatNeedAnUpdate, Library library, DateTime updateStartTime) in d:\a\1\s\EmbyStat.Jobs\Jobs\Sync\MediaSyncJob.cs:line 267
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessShowsAsync(IEnumerable`1 libraries, CancellationToken cancellationToken) in d:\a\1\s\EmbyStat.Jobs\Jobs\Sync\MediaSyncJob.cs:line 204
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync() in d:\a\1\s\EmbyStat.Jobs\Jobs\Sync\MediaSyncJob.cs:line 85
   at EmbyStat.Jobs.BaseJob.Execute() in d:\a\1\s\EmbyStat.Jobs\BaseJob.cs:line 54

**Comment by Sc4nd4l** [comment]
Same here, still buggy with the media sync 

`2019-11-13 18:09:51.8809 [ERROR] Error in event handler System.InvalidCastException: Unable to cast object of type 'LiteDB.DataPage' to type 'LiteDB.IndexPage'.
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.PageService.GetFreePage[T](UInt32 startPageID, Int32 size)
   at LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, Byte level, IndexNode last)
   at LiteDB.LiteEngine.InsertDocument(CollectionPage col, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteEngine.<>c__DisplayClass22_0.<Insert>b__0(CollectionPage col)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteCollection`1.Insert(T document)
   at EmbyStat.Repositories.SessionRepository.<>c__DisplayClass6_0.<CreateSession>b__0() in d:\a\1\s\EmbyStat.Repositories\SessionRepository.cs:line 64
   at EmbyStat.Repositories.BaseRepository.ExecuteQuery(Action query) in d:\a\1\s\EmbyStat.Repositories\BaseRepository.cs:line 29
   at EmbyStat.Services.SessionService.ProcessSessions(List`1 sessions) in d:\a\1\s\EmbyStat.Services\SessionService.cs:line 36
   at EmbyStat.Services.WebSocketService.WebSocketApiSessionsUpdated(Object sender, GenericEventArgs`1 e) in d:\a\1\s\EmbyStat.Services\WebSocketService.cs:line 107
   at EmbyStat.Clients.Emby.WebSocket.WebSocketApi.FireEvent[T](EventHandler`1 handler, Object sender, T args) in d:\a\1\s\EmbyStat.Clients.Emby.WebSocket\WebSocketApi.cs:line 212
2019-11-13 18:09:52.3127 [INFO] MEDIASYNC-JOB	Processed 600 / 6948 movies 
2019-11-13 18:09:53.1009 [INFO] MEDIASYNC-JOB	Processed 700 / 6948 movies 
2019-11-13 18:09:53.7912 [INFO] MEDIASYNC-JOB	Processed 800 / 6948 movies 
2019-11-13 18:09:54.5004 [INFO] MEDIASYNC-JOB	Processed 900 / 6948 movies 
2019-11-13 18:09:55.1325 [INFO] MEDIASYNC-JOB	Processed 1000 / 6948 movies 
2019-11-13 18:09:55.4681 [ERROR] Error while running job System.Collections.Generic.KeyNotFoundException: The given key '40' was not present `

**Comment by mregni** [comment]
That 'LiteDB.DataPage' to type 'LiteDB.IndexPage' exception is something from LiteDB and seems hard to fix :( On the github page it looks like the error happens at random so need to find a way to fix that. 

I also just saw that V5 of LiteDB is in beta, going to wait a bit more but looks promising to move to V5 asap.

@jaycedk, join to open a new issue for your log because that looks like a bug in EmbyStat. It should find the show if it already exists.

**Comment by mregni** [comment]
I just updated to LiteDB V5 in beta.18. Can you install it as a clean install and check if the problem is still there?
