### ISSUE TITLE
Moved show on server throws duplicate key error

### ISSUE THREAD

**Issue by mregni** [mregni/EmbyStat#981]
Hi im also seeing some sync errors.
Im on EmbyStat version: 0.2.0-beta.13
Its probably my own doing i moves some shows to a different folder.
2019-11-13 18:16:55.6020 [ERROR] Error while running job LiteDB.LiteException: Cannot insert duplicate key in unique index '_id'. The duplicate value is '145990'.
   at LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, Byte level, IndexNode last)
   at LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, IndexNode last)
   at LiteDB.LiteEngine.InsertDocument(CollectionPage col, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteEngine.<>c__DisplayClass22_0.<Insert>b__0(CollectionPage col)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.InsertBulk(String collection, IEnumerable`1 docs, Int32 batchSize, BsonType autoId)
   at LiteDB.LiteCollection`1.InsertBulk(IEnumerable`1 docs, Int32 batchSize)
   at EmbyStat.Repositories.ShowRepository.<>c__DisplayClass5_0.<UpsertShow>b__0() in d:\a\1\s\EmbyStat.Repositories\ShowRepository.cs:line 90
   at EmbyStat.Repositories.BaseRepository.ExecuteQuery(Action query) in d:\a\1\s\EmbyStat.Repositories\BaseRepository.cs:line 29
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.PerformShowSyncAsync(IReadOnlyList`1 showsThatNeedAnUpdate, Library library, DateTime updateStartTime) in d:\a\1\s\EmbyStat.Jobs\Jobs\Sync\MediaSyncJob.cs:line 267
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessShowsAsync(IEnumerable`1 libraries, CancellationToken cancellationToken) in d:\a\1\s\EmbyStat.Jobs\Jobs\Sync\MediaSyncJob.cs:line 204
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync() in d:\a\1\s\EmbyStat.Jobs\Jobs\Sync\MediaSyncJob.cs:line 85
   at EmbyStat.Jobs.BaseJob.Execute() in d:\a\1\s\EmbyStat.Jobs\BaseJob.cs:line 54

_Originally posted by @jaycedk in https://github.com/mregni/EmbyStat/issues/978#issuecomment-553506021_

**Comment by jaycedk** [comment]
Hi here is the complete log.
As i said, I moved some folders around.
And made a cartoon folder and added it to emby, as a tvshow, but under a diffrent name.
I deleded the whole embystats folder, and re-extracted the new release, " right-click unblock" extract.
New Embystats and new rebuild of embystats db.
Hope any of this makes any sence :) 
I did however run a full scan in emby on the old folder and the new before starting the new release of embystats. it might be old bad entries in the emby db. 
[2019-11-13.log](https://github.com/mregni/EmbyStat/files/3848503/2019-11-13.log)

**Comment by mregni** [comment]
Thanks for the log. 

That means that the old show is already in EmbyStat and it just wants to add the new one (and fails on the duplicate key). The last step of the show sync process is removing all shows that are no longer in Emby. But since you are in a situation it fails on the insert I will need to fix that he will continue so on the next sync the new one should be added like a new show.

**Comment by jaycedk** [comment]
ok :)
But I can test further, and delete the embystats folder and start from scratch.
Just to test it.

**Comment by jaycedk** [comment]
Total new embystat test.
Start from scratch.
Same error on first sync run.

**Comment by jaycedk** [comment]
Hmm some how the sync worked today :)
Here is the log
[2019-11-18.log](https://github.com/mregni/EmbyStat/files/3860110/2019-11-18.log)

**Comment by mregni** [comment]
Hehehe, there still seems to be a problem with the show sync. That NullRef exception should not be there. I'll have a look later on.

**Comment by mregni** [comment]
This should be fixed when the fix for #1007 is merged because I changed all inserts to upserts were needed to prevent duplicate keys.

**Comment by jaycedk** [comment]
You can close this :)
Your hard work fixed the issue :)

**Comment by mregni** [comment]
Thanks for the update!
